# python version 1.0						DO NOT EDIT
#
# Generated by smidump version 0.4.8:
#
#   smidump -f python HP-ICF-CHASSIS

FILENAME = "./HP-ICF-CHASSIS.mib"

MIB = {
    "moduleName" : "HP-ICF-CHASSIS",

    "HP-ICF-CHASSIS" : {
        "nodetype" : "module",
        "language" : "SMIv2",
        "organization" :    
            """Hewlett Packard Company,
Network Infrastructure Solutions""",
        "contact" : 
            """Hewlett Packard Company
8000 Foothills Blvd.
Roseville, CA 95747""",
        "description" :
            """This MIB module describes chassis devices in the
HP Integrated Communication Facility product 
line.  Note that most of this module will be
superceded by the standard Entity MIB.  However,
the hpicfSensorTable will still be valid.""",
        "revisions" : (
            {
                "date" : "2000-11-03 22:16",
                "description" :
                    """Updated division name.""",
            },
            {
                "date" : "1997-03-06 03:34",
                "description" :
                    """Added NOTIFICATION-GROUP information.""",
            },
            {
                "date" : "1996-09-10 02:45",
                "description" :
                    """Split this MIB module from the former monolithic
hp-icf MIB.  Added compliance statement for use by
non-chassis devices or devices that are
implementing another chassis MIB (like Entity MIB)
but still want to use the hpicfSensorTable.
Changed STATUS clause to deprecated for those
objects that are superceded by the Entity MIB.""",
            },
            {
                "date" : "1995-07-13 00:00",
                "description" :
                    """Added the hpicfSensorTrap.""",
            },
            {
                "date" : "1994-11-20 00:00",
                "description" :
                    """Added the hpicfChassisAddrTable.""",
            },
            {
                "date" : "1993-07-09 00:00",
                "description" :
                    """Initial version.""",
            },
        ),
        "identity node" : "hpicfChassisMib",
    },

    "imports" : (
        {"module" : "SNMPv2-SMI", "name" : "Integer32"},
        {"module" : "SNMPv2-SMI", "name" : "Counter32"},
        {"module" : "SNMPv2-SMI", "name" : "OBJECT-TYPE"},
        {"module" : "SNMPv2-SMI", "name" : "MODULE-IDENTITY"},
        {"module" : "SNMPv2-SMI", "name" : "NOTIFICATION-TYPE"},
        {"module" : "SNMPv2-TC", "name" : "DisplayString"},
        {"module" : "SNMPv2-TC", "name" : "TimeStamp"},
        {"module" : "SNMPv2-CONF", "name" : "MODULE-COMPLIANCE"},
        {"module" : "SNMPv2-CONF", "name" : "OBJECT-GROUP"},
        {"module" : "SNMPv2-CONF", "name" : "NOTIFICATION-GROUP"},
        {"module" : "HP-ICF-OID", "name" : "hpicfObjectModules"},
        {"module" : "HP-ICF-OID", "name" : "hpicfCommon"},
        {"module" : "HP-ICF-OID", "name" : "hpicfCommonTrapsPrefix"},
    ),

    "nodes" : {
        "hpicfChassisMib" : {
            "nodetype" : "node",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.10.2.3",
            "status" : "current",
        }, # node
        "hpicfChassisConformance" : {
            "nodetype" : "node",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.10.2.3.1",
        }, # node
        "hpicfChassisCompliances" : {
            "nodetype" : "node",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.10.2.3.1.1",
        }, # node
        "hpicfChassisGroups" : {
            "nodetype" : "node",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.10.2.3.1.2",
        }, # node
        "hpicfChassis" : {
            "nodetype" : "node",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2",
        }, # node
        "hpicfChassisId" : {
            "nodetype" : "scalar",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.1",
            "status" : "deprecated",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "ranges" : [
                    {
                        "min" : "6",
                        "max" : "6"
                    },
                    ],
                    "range" : {
                        "min" : "6",
                        "max" : "6"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """********* THIS OBJECT IS DEPRECATED *********

An identifier that uniquely identifies this 
particular chassis.  This will be the same value 
as the instance of hpicfChainId for this chassis.""",
        }, # scalar
        "hpicfChassisNumSlots" : {
            "nodetype" : "scalar",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.2",
            "status" : "deprecated",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "16"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "16"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """********* THIS OBJECT IS DEPRECATED *********

The number of slots in this chassis.""",
        }, # scalar
        "hpicfSlotTable" : {
            "nodetype" : "table",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.3",
            "status" : "deprecated",
            "description" :
                """********* THIS OBJECT IS DEPRECATED *********

A table that contains information on all the 
slots in this chassis.""",
        }, # table
        "hpicfSlotEntry" : {
            "nodetype" : "row",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.3.1",
            "status" : "deprecated",
            "linkage" : [
                "hpicfSlotIndex",
            ],
            "description" :
                """********* THIS OBJECT IS DEPRECATED *********

Information about a slot in a chassis""",
        }, # row
        "hpicfSlotIndex" : {
            "nodetype" : "column",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.3.1.1",
            "status" : "deprecated",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "16"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "16"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """********* THIS OBJECT IS DEPRECATED *********

The slot number within the box for which this 
entry contains information.""",
        }, # column
        "hpicfSlotObjectId" : {
            "nodetype" : "column",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.3.1.2",
            "status" : "deprecated",
            "syntax" : {
                "type" : { "module" :"", "name" : "ObjectIdentifier"},
            },
            "access" : "readonly",
            "description" :
                """********* THIS OBJECT IS DEPRECATED *********

The authoritative identification of the card 
plugged into this slot in this chassis.  A value 
of { 0 0 } indicates an empty slot.""",
        }, # column
        "hpicfSlotLastChange" : {
            "nodetype" : "column",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.3.1.3",
            "status" : "deprecated",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "TimeStamp"},
            },
            "access" : "readonly",
            "description" :
                """********* THIS OBJECT IS DEPRECATED *********

The value of the agent's sysUpTime at which a 
card in this slot was last inserted or removed.  
If no module has been inserted or removed since 
the last reinitialization of the agent, this 
object has a zero value.""",
        }, # column
        "hpicfSlotDescr" : {
            "nodetype" : "column",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.3.1.4",
            "status" : "deprecated",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "SNMPv2-TC",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "255"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "255"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """********* THIS OBJECT IS DEPRECATED *********

A textual description of the card plugged into 
this slot in this chassis, including the product 
number and version information.""",
        }, # column
        "hpicfEntityTable" : {
            "nodetype" : "table",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.4",
            "status" : "deprecated",
            "description" :
                """********* THIS OBJECT IS DEPRECATED *********

A table that contains information about the 
(logical) networking devices contained in this
chassis.""",
        }, # table
        "hpicfEntityEntry" : {
            "nodetype" : "row",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.4.1",
            "status" : "deprecated",
            "linkage" : [
                "hpicfEntityIndex",
            ],
            "description" :
                """********* THIS OBJECT IS DEPRECATED *********

Information about a single logical networking 
device contained in this chassis.""",
        }, # row
        "hpicfEntityIndex" : {
            "nodetype" : "column",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.4.1.1",
            "status" : "deprecated",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "16"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "16"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """********* THIS OBJECT IS DEPRECATED *********

An index that uniquely identifies the logical 
network device for which this entry contains 
information.""",
        }, # column
        "hpicfEntityFunction" : {
            "nodetype" : "column",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.4.1.2",
            "status" : "deprecated",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "63"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "63"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """********* THIS OBJECT IS DEPRECATED *********

The generic function provided by the logical 
network device.  The value is a sum.  Starting 
from zero, for each type of generic function that 
the entity performs, 2 raised to a power is added 
to the sum.  The powers are according to the 
following table:

    Function        Power
    other           1
    repeater        0
    bridge          2
    router          3
    agent           5

For example, an entity performing both bridging 
and routing functions would have a value of 12 
(2^2 + 2^3).""",
        }, # column
        "hpicfEntityObjectId" : {
            "nodetype" : "column",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.4.1.3",
            "status" : "deprecated",
            "syntax" : {
                "type" : { "module" :"", "name" : "ObjectIdentifier"},
            },
            "access" : "readonly",
            "description" :
                """********* THIS OBJECT IS DEPRECATED *********

The authoritative identification of the logical 
network device which provides an unambiguous means
of determining the type of device.  The value of 
this object is analagous to MIB-II's sysObjectId.""",
        }, # column
        "hpicfEntityDescr" : {
            "nodetype" : "column",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.4.1.4",
            "status" : "deprecated",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "parent module" : {
                        "name" : "SNMPv2-TC",
                        "type" : "DisplayString",
                    },
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "255"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "255"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """********* THIS OBJECT IS DEPRECATED *********

A textual description of this device, including 
the product number and version information.  The 
value of this object is analogous to MIB-II's 
sysDescr.""",
        }, # column
        "hpicfEntityTimestamp" : {
            "nodetype" : "column",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.4.1.5",
            "status" : "deprecated",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "TimeStamp"},
            },
            "access" : "readonly",
            "description" :
                """********* THIS OBJECT IS DEPRECATED *********

The value of the agent's sysUpTime at which this 
logical network device was last reinitialized.  If
the entity has not been reinitialized since the 
last reinitialization of the agent, then this 
object has a zero value.""",
        }, # column
        "hpicfSlotMapTable" : {
            "nodetype" : "table",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.5",
            "status" : "deprecated",
            "description" :
                """********* THIS OBJECT IS DEPRECATED *********

A table that contains information about which 
entities are in which slots in this chassis.""",
        }, # table
        "hpicfSlotMapEntry" : {
            "nodetype" : "row",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.5.1",
            "status" : "deprecated",
            "linkage" : [
                "hpicfSlotMapSlot",
                "hpicfSlotMapEntity",
            ],
            "description" :
                """********* THIS OBJECT IS DEPRECATED *********

A relationship between a slot and an entity in
this chassis.  Such a relationship exists if the 
particular slot is occupied by a physical module 
performing part of the function of the particular 
entity.""",
        }, # row
        "hpicfSlotMapSlot" : {
            "nodetype" : "column",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.5.1.1",
            "status" : "deprecated",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "16"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "16"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """********* THIS OBJECT IS DEPRECATED *********

A slot number within the chassis which contains 
(part of) this entity.""",
        }, # column
        "hpicfSlotMapEntity" : {
            "nodetype" : "column",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.5.1.2",
            "status" : "deprecated",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "16"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "16"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """********* THIS OBJECT IS DEPRECATED *********

The entity described in this mapping.""",
        }, # column
        "hpicfSensorTable" : {
            "nodetype" : "table",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.6",
            "status" : "current",
            "description" :
                """A table that contains information on all the
sensors in this chassis""",
        }, # table
        "hpicfSensorEntry" : {
            "nodetype" : "row",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.6.1",
            "status" : "current",
            "linkage" : [
                "hpicfSensorIndex",
            ],
            "description" :
                """Information about a sensor in a chassis""",
        }, # row
        "hpicfSensorIndex" : {
            "nodetype" : "column",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.6.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "2147483647"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "2147483647"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """An index that uniquely identifies the sensor for
which this entry contains information.""",
        }, # column
        "hpicfSensorObjectId" : {
            "nodetype" : "column",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.6.1.2",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "ObjectIdentifier"},
            },
            "access" : "readonly",
            "description" :
                """The authoritative identification of the kind of
sensor this is.""",
        }, # column
        "hpicfSensorNumber" : {
            "nodetype" : "column",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.6.1.3",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Integer32"},
            },
            "access" : "readonly",
            "description" :
                """A number which identifies a particular sensor
from other sensors of the same kind.  For
instance, if there are many temperature sensors in
this chassis, this number whould identify a
particular temperature sensor in this chassis.""",
        }, # column
        "hpicfSensorStatus" : {
            "nodetype" : "column",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.6.1.4",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "unknown" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "bad" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                    "warning" : {
                        "nodetype" : "namednumber",
                        "number" : "3"
                    },
                    "good" : {
                        "nodetype" : "namednumber",
                        "number" : "4"
                    },
                    "notPresent" : {
                        "nodetype" : "namednumber",
                        "number" : "5"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Actual status indicated by the sensor.""",
        }, # column
        "hpicfSensorWarnings" : {
            "nodetype" : "column",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.6.1.5",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-SMI", "name" : "Counter32"},
            },
            "access" : "readonly",
            "description" :
                """The number of times hpicfSensorStatus has entered
the 'warning'(3) state.""",
        }, # column
        "hpicfSensorFailures" : {
            "nodetype" : "column",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.6.1.6",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-SMI", "name" : "Counter32"},
            },
            "access" : "readonly",
            "description" :
                """The number of times hpicfSensorStatus has entered
the 'bad'(2) state.""",
        }, # column
        "hpicfSensorDescr" : {
            "nodetype" : "column",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.6.1.7",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"SNMPv2-TC", "name" : "DisplayString"},
            },
            "access" : "readonly",
            "description" :
                """A textual description of the sensor.""",
        }, # column
        "hpicfChassisAddrTable" : {
            "nodetype" : "table",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.7",
            "status" : "deprecated",
            "description" :
                """********* THIS OBJECT IS DEPRECATED *********

A table of network addresses for entities in this
chassis.  The primary use of this table is to map
a specific entity address to a specific chassis.
Note that this table may not be a complete list of
network addresses for this entity.""",
        }, # table
        "hpicfChassisAddrEntry" : {
            "nodetype" : "row",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.7.1",
            "status" : "deprecated",
            "linkage" : [
                "hpicfChasAddrType",
                "hpicfChasAddrAddress",
            ],
            "description" :
                """********* THIS OBJECT IS DEPRECATED *********

An entry containing a single network address being
used by a logical network device in this chassis.""",
        }, # row
        "hpicfChasAddrType" : {
            "nodetype" : "column",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.7.1.1",
            "status" : "deprecated",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Enumeration",
                    "ipAddr" : {
                        "nodetype" : "namednumber",
                        "number" : "1"
                    },
                    "ipxAddr" : {
                        "nodetype" : "namednumber",
                        "number" : "2"
                    },
                    "macAddr" : {
                        "nodetype" : "namednumber",
                        "number" : "3"
                    },
                },
            },
            "access" : "noaccess",
            "description" :
                """********* THIS OBJECT IS DEPRECATED *********

The kind of network address represented in this
entry.""",
        }, # column
        "hpicfChasAddrAddress" : {
            "nodetype" : "column",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.7.1.2",
            "status" : "deprecated",
            "syntax" : {
                "type" :                 {
                    "basetype" : "OctetString",
                    "ranges" : [
                    {
                        "min" : "4",
                        "max" : "10"
                    },
                    ],
                    "range" : {
                        "min" : "4",
                        "max" : "10"
                    },
                },
            },
            "access" : "noaccess",
            "description" :
                """********* THIS OBJECT IS DEPRECATED *********

The network address being used by the logical
network device associated with this entry, formatted
according to the value of the associated instance of
hpicfChasAddrType.

For hpicfChasAddrType of ipAddr, this value is four
octets long, with each octet representing one byte of
the IP address, in network byte order.

For hpicfChasAddrType of ipxAddr, this value is ten
octets long, with the first four octets representing
the IPX network number in network byte order,
followed by the six byte host number in network byte
order.

For hpicfChasAddrType of macAddr, this value is six
octets long, representing the MAC address in
canonical order.""",
        }, # column
        "hpicfChasAddrEntity" : {
            "nodetype" : "column",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.11.1.2.7.1.3",
            "status" : "deprecated",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "16"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "16"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """********* THIS OBJECT IS DEPRECATED *********

An index that uniquely identifies the logical 
network device in this chassis that is using this
network address..""",
        }, # column
    }, # nodes

    "notifications" : {
        "hpicfSensorTrap" : {
            "nodetype" : "notification",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.12.1.0.3",
            "status" : "current",
            "objects" : {
                "hpicfSensorStatus" : {
                    "nodetype" : "object",
                    "module" : "HP-ICF-CHASSIS"
                },
                "hpicfSensorDescr" : {
                    "nodetype" : "object",
                    "module" : "HP-ICF-CHASSIS"
                },
            },
            "description" :
                """An hpicfSensorTrap indicates that there has been a
change of state on one of the sensors in this
chassis.  The hpicfSensorStatus indicates the new
status value for the changed sensor.""",
        }, # notification
    }, # notifications

    "groups" : {
        "hpicfChassisBasicGroup" : {
            "nodetype" : "group",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.10.2.3.1.2.1",
            "status" : "deprecated",
            "members" : {
                "hpicfChassisId" : {
                    "nodetype" : "member",
                    "module" : "HP-ICF-CHASSIS"
                },
                "hpicfChassisNumSlots" : {
                    "nodetype" : "member",
                    "module" : "HP-ICF-CHASSIS"
                },
                "hpicfSlotIndex" : {
                    "nodetype" : "member",
                    "module" : "HP-ICF-CHASSIS"
                },
                "hpicfSlotObjectId" : {
                    "nodetype" : "member",
                    "module" : "HP-ICF-CHASSIS"
                },
                "hpicfSlotLastChange" : {
                    "nodetype" : "member",
                    "module" : "HP-ICF-CHASSIS"
                },
                "hpicfSlotDescr" : {
                    "nodetype" : "member",
                    "module" : "HP-ICF-CHASSIS"
                },
                "hpicfEntityIndex" : {
                    "nodetype" : "member",
                    "module" : "HP-ICF-CHASSIS"
                },
                "hpicfEntityFunction" : {
                    "nodetype" : "member",
                    "module" : "HP-ICF-CHASSIS"
                },
                "hpicfEntityObjectId" : {
                    "nodetype" : "member",
                    "module" : "HP-ICF-CHASSIS"
                },
                "hpicfEntityDescr" : {
                    "nodetype" : "member",
                    "module" : "HP-ICF-CHASSIS"
                },
                "hpicfEntityTimestamp" : {
                    "nodetype" : "member",
                    "module" : "HP-ICF-CHASSIS"
                },
                "hpicfSlotMapSlot" : {
                    "nodetype" : "member",
                    "module" : "HP-ICF-CHASSIS"
                },
                "hpicfSlotMapEntity" : {
                    "nodetype" : "member",
                    "module" : "HP-ICF-CHASSIS"
                },
            }, # members
            "description" :
                """********* THIS GROUP IS DEPRECATED *********

A collection of objects for determining the
contents of an ICF chassis device.""",
        }, # group
        "hpicfSensorGroup" : {
            "nodetype" : "group",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.10.2.3.1.2.2",
            "status" : "current",
            "members" : {
                "hpicfSensorIndex" : {
                    "nodetype" : "member",
                    "module" : "HP-ICF-CHASSIS"
                },
                "hpicfSensorObjectId" : {
                    "nodetype" : "member",
                    "module" : "HP-ICF-CHASSIS"
                },
                "hpicfSensorNumber" : {
                    "nodetype" : "member",
                    "module" : "HP-ICF-CHASSIS"
                },
                "hpicfSensorStatus" : {
                    "nodetype" : "member",
                    "module" : "HP-ICF-CHASSIS"
                },
                "hpicfSensorWarnings" : {
                    "nodetype" : "member",
                    "module" : "HP-ICF-CHASSIS"
                },
                "hpicfSensorFailures" : {
                    "nodetype" : "member",
                    "module" : "HP-ICF-CHASSIS"
                },
                "hpicfSensorDescr" : {
                    "nodetype" : "member",
                    "module" : "HP-ICF-CHASSIS"
                },
            }, # members
            "description" :
                """A collection of objects for monitoring the status
of sensors in an ICF chassis.""",
        }, # group
        "hpicfChassisAddrGroup" : {
            "nodetype" : "group",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.10.2.3.1.2.3",
            "status" : "deprecated",
            "members" : {
                "hpicfChasAddrEntity" : {
                    "nodetype" : "member",
                    "module" : "HP-ICF-CHASSIS"
                },
            }, # members
            "description" :
                """********* THIS GROUP IS DEPRECATED *********

A collection of objects to allow a management
station to determine which devices are in the same
chassis.""",
        }, # group
        "hpicfSensorNotifyGroup" : {
            "nodetype" : "group",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.10.2.3.1.2.4",
            "status" : "current",
            "members" : {
                "hpicfSensorTrap" : {
                    "nodetype" : "member",
                    "module" : "HP-ICF-CHASSIS"
                },
            }, # members
            "description" :
                """A collection of notifications used to indicate
changes in the status of sensors.""",
        }, # group
    }, # groups

    "compliances" : {
        "hpicfChasAdvStkCompliance" : {
            "nodetype" : "compliance",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.10.2.3.1.1.1",
            "status" : "deprecated",
            "description" :
                """********* THIS COMPLIANCE IS DEPRECATED *********

A compliance statement for AdvanceStack chassis
devices.""",
            "requires" : {
                "hpicfChassisBasicGroup" : {
                    "nodetype" : "mandatory",
                    "module" : "HP-ICF-CHASSIS"
                },
                "hpicfSensorGroup" : {
                    "nodetype" : "optional",
                    "module" : "HP-ICF-CHASSIS",
                    "description" :
                        """This group should be implemented on any
AdvanceStack device with redundant power
supplies or other appropriate sensors.""",
                },
                "hpicfSensorNotifyGroup" : {
                    "nodetype" : "optional",
                    "module" : "HP-ICF-CHASSIS",
                    "description" :
                        """This group should be implemented on any
AdvanceStack device with redundant power
supplies or other appropriate sensors.""",
                },
            }, # requires
        }, # compliance
        "hpicfChasAdvStk2Compliance" : {
            "nodetype" : "compliance",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.10.2.3.1.1.2",
            "status" : "deprecated",
            "description" :
                """********* THIS COMPLIANCE IS DEPRECATED *********

An updated compliance statement for AdvanceStack
chassis devices that includes the
hpicfChassisAddrGroup.""",
            "requires" : {
                "hpicfChassisBasicGroup" : {
                    "nodetype" : "mandatory",
                    "module" : "HP-ICF-CHASSIS"
                },
                "hpicfChassisAddrGroup" : {
                    "nodetype" : "mandatory",
                    "module" : "HP-ICF-CHASSIS"
                },
                "hpicfSensorGroup" : {
                    "nodetype" : "optional",
                    "module" : "HP-ICF-CHASSIS",
                    "description" :
                        """This group should be implemented on any
AdvanceStack device with redundant power
supplies or other appropriate sensors.""",
                },
                "hpicfSensorNotifyGroup" : {
                    "nodetype" : "optional",
                    "module" : "HP-ICF-CHASSIS",
                    "description" :
                        """This group should be implemented on any
AdvanceStack device with redundant power
supplies or other appropriate sensors.""",
                },
            }, # requires
        }, # compliance
        "hpicfChasSensorCompliance" : {
            "nodetype" : "compliance",
            "moduleName" : "HP-ICF-CHASSIS",
            "oid" : "1.3.6.1.4.1.11.2.14.10.2.3.1.1.3",
            "status" : "current",
            "description" :
                """A compliance statement for non-chassis devices,
or chassis devices implementing a standards-based
MIB for obtaining chassis information, which
contain redundant power supplies or other
appropriate sensors.""",
            "requires" : {
                "hpicfSensorGroup" : {
                    "nodetype" : "mandatory",
                    "module" : "HP-ICF-CHASSIS"
                },
                "hpicfSensorNotifyGroup" : {
                    "nodetype" : "mandatory",
                    "module" : "HP-ICF-CHASSIS"
                },
            }, # requires
        }, # compliance
    }, # compliances

}
