# python version 1.0						DO NOT EDIT
#
# Generated by smidump version 0.4.8:
#
#   smidump -f python IT-WATCHDOGS-V4-MIB

FILENAME = "IT-WATCHDOGS-V4-MIB.mib"

MIB = {
    "moduleName" : "IT-WATCHDOGS-V4-MIB",

    "IT-WATCHDOGS-V4-MIB" : {
        "nodetype" : "module",
        "language" : "SMIv1",
        "organization" :
            """I.T. Watchdogs""",
        "contact" :
            """support@itwatchdogs.com""",
        "description" :
            """The MIB for I.T. Watchdogs Products""",
        "revisions" : (
            {
                "date" : "2012-09-11 00:00",
                "description" :
                    """Original version""",
            },
        ),
        "identity node" : "itwatchdogs",
    },

    "imports" : (
        {"module" : "SNMPv2-TC", "name" : "DisplayString"},
        {"module" : "SNMPv2-SMI", "name" : "MODULE-IDENTITY"},
        {"module" : "SNMPv2-SMI", "name" : "OBJECT-TYPE"},
        {"module" : "SNMPv2-SMI", "name" : "IpAddress"},
        {"module" : "SNMPv2-SMI", "name" : "enterprises"},
        {"module" : "SNMPv2-SMI", "name" : "Integer32"},
        {"module" : "SNMPv2-SMI", "name" : "Gauge32"},
        {"module" : "SNMPv2-SMI", "name" : "NOTIFICATION-TYPE"},
    ),

    "nodes" : {
        "itwatchdogs" : {
            "nodetype" : "node",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373",
            "status" : "current",
        }, # node
        "blackbird" : {
            "nodetype" : "node",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4",
        }, # node
        "watchdog100" : {
            "nodetype" : "node",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1",
        }, # node
        "deviceInfo" : {
            "nodetype" : "node",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.1",
        }, # node
        "productTitle" : {
            "nodetype" : "scalar",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.1.1",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Product name""",
        }, # scalar
        "productVersion" : {
            "nodetype" : "scalar",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.1.2",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Product version""",
        }, # scalar
        "productFriendlyName" : {
            "nodetype" : "scalar",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.1.3",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """User-assigned name""",
        }, # scalar
        "productMacAddress" : {
            "nodetype" : "scalar",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.1.4",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "OctetString"},
            },
            "access" : "readonly",
            "description" :
                """Product's unique MAC address""",
        }, # scalar
        "productUrl" : {
            "nodetype" : "scalar",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.1.5",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Product's main URL access point""",
        }, # scalar
        "deviceCount" : {
            "nodetype" : "scalar",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.1.6",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "100"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Total number of devices on unit""",
        }, # scalar
        "temperatureUnits" : {
            "nodetype" : "scalar",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.1.7",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "1"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "1"
                    },
                },
            },
            "access" : "readwrite",
            "description" :
                """Current units for temperature values. 0 = Degrees Fahrenheit, 1 = Degrees Celsius""",
        }, # scalar
        "internalTable" : {
            "nodetype" : "table",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.2",
            "status" : "current",
            "description" :
                """Internal sensors for units""",
        }, # table
        "internalEntry" : {
            "nodetype" : "row",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.2.1",
            "status" : "current",
            "linkage" : [
                "internalIndex",
            ],
            "description" :
                """Entry in the internalTable table: each entry contains an index and other sensor details""",
        }, # row
        "internalIndex" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.2.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "100"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Table entry index value""",
        }, # column
        "internalSerial" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.2.1.2",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Serial Number""",
        }, # column
        "internalName" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.2.1.3",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Friendly Name""",
        }, # column
        "internalAvail" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.2.1.4",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Is device currently plugged in?""",
        }, # column
        "internalTemp" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.2.1.5",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "-40",
                        "max" : "200"
                    },
                    ],
                    "range" : {
                        "min" : "-40",
                        "max" : "200"
                    },
                },
            },
            "access" : "readonly",
            "units" : "0.1 Degrees",
            "description" :
                """Current reading for Temperature in tenths of degrees. Units are given by temperatureUnits field in deviceInfo""",
        }, # column
        "internalHumidity" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.2.1.6",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "100"
                    },
                },
            },
            "access" : "readonly",
            "units" : "%",
            "description" :
                """Humidity reading""",
        }, # column
        "internalDewPoint" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.2.1.7",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "-40",
                        "max" : "200"
                    },
                    ],
                    "range" : {
                        "min" : "-40",
                        "max" : "200"
                    },
                },
            },
            "access" : "readonly",
            "units" : "0.1 Degrees",
            "description" :
                """Current reading for Dew-point in tenths of degrees. Units are given by temperatureUnits field in deviceInfo""",
        }, # column
        "internalIO1" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.2.1.8",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "100"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Current reading for Analog Input 1""",
        }, # column
        "internalIO2" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.2.1.9",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "100"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Current reading for Analog Input 2""",
        }, # column
        "internalIO3" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.2.1.10",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "100"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Current reading for Analog Input 3""",
        }, # column
        "internalIO4" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.2.1.11",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "100"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Current reading for Analog Input 4""",
        }, # column
        "internalRelayState" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.2.1.12",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Is the relay on?""",
        }, # column
        "tempSensorTable" : {
            "nodetype" : "table",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.4",
            "status" : "current",
            "description" :
                """Remote Temperature Sensor""",
        }, # table
        "tempSensorEntry" : {
            "nodetype" : "row",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.4.1",
            "status" : "current",
            "linkage" : [
                "tempSensorIndex",
            ],
            "description" :
                """Entry in the tempSensorTable table: each entry contains an index and other sensor details""",
        }, # row
        "tempSensorIndex" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.4.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "100"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Table entry index value""",
        }, # column
        "tempSensorSerial" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.4.1.2",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Serial Number""",
        }, # column
        "tempSensorName" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.4.1.3",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Friendly Name""",
        }, # column
        "tempSensorAvail" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.4.1.4",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Is device currently plugged in?""",
        }, # column
        "tempSensorTemp" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.4.1.5",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "-40",
                        "max" : "200"
                    },
                    ],
                    "range" : {
                        "min" : "-40",
                        "max" : "200"
                    },
                },
            },
            "access" : "readonly",
            "units" : "0.1 Degrees",
            "description" :
                """Current reading for Temperature in tenths of degrees. Units are given by temperatureUnits field in deviceInfo""",
        }, # column
        "airFlowSensorTable" : {
            "nodetype" : "table",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.5",
            "status" : "current",
            "description" :
                """Remote Airflow, Humidity, Temperature and Dewpoint Sensor """,
        }, # table
        "airFlowSensorEntry" : {
            "nodetype" : "row",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.5.1",
            "status" : "current",
            "linkage" : [
                "airFlowSensorIndex",
            ],
            "description" :
                """Entry in the airFlowSensorTable table: each entry contains an index and other sensor details""",
        }, # row
        "airFlowSensorIndex" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.5.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "100"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Table entry index value""",
        }, # column
        "airFlowSensorSerial" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.5.1.2",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Serial Number""",
        }, # column
        "airFlowSensorName" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.5.1.3",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Friendly Name""",
        }, # column
        "airFlowSensorAvail" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.5.1.4",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Is device currently plugged in?""",
        }, # column
        "airFlowSensorTemp" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.5.1.5",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "-40",
                        "max" : "200"
                    },
                    ],
                    "range" : {
                        "min" : "-40",
                        "max" : "200"
                    },
                },
            },
            "access" : "readonly",
            "units" : "0.1 Degrees",
            "description" :
                """Current reading for Temperature in tenths of degrees. Units are given by temperatureUnits field in deviceInfo""",
        }, # column
        "airFlowSensorFlow" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.5.1.6",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "100"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """AFHT3 Airflow reading""",
        }, # column
        "airFlowSensorHumidity" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.5.1.7",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "100"
                    },
                },
            },
            "access" : "readonly",
            "units" : "%",
            "description" :
                """AFHT3 Humidity reading""",
        }, # column
        "airFlowSensorDewPoint" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.5.1.8",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "-40",
                        "max" : "200"
                    },
                    ],
                    "range" : {
                        "min" : "-40",
                        "max" : "200"
                    },
                },
            },
            "access" : "readonly",
            "units" : "0.1 Degrees",
            "description" :
                """Current reading for Dew Point in tenths of degrees. Units are given by temperatureUnits field in deviceInfo""",
        }, # column
        "dewPointSensorTable" : {
            "nodetype" : "table",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.6",
            "status" : "current",
            "description" :
                """Remote Dew Point sensor""",
        }, # table
        "dewPointSensorEntry" : {
            "nodetype" : "row",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.6.1",
            "status" : "current",
            "linkage" : [
                "dewPointSensorIndex",
            ],
            "description" :
                """Entry in the dewPointSensorTable table: each entry contains an index and other sensor details""",
        }, # row
        "dewPointSensorIndex" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.6.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "100"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Table entry index value""",
        }, # column
        "dewPointSensorSerial" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.6.1.2",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Serial Number""",
        }, # column
        "dewPointSensorName" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.6.1.3",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Friendly Name""",
        }, # column
        "dewPointSensorAvail" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.6.1.4",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Is device currently plugged in?""",
        }, # column
        "dewPointSensorTemp" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.6.1.5",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "-40",
                        "max" : "200"
                    },
                    ],
                    "range" : {
                        "min" : "-40",
                        "max" : "200"
                    },
                },
            },
            "access" : "readonly",
            "units" : "0.1 Degrees",
            "description" :
                """Current reading for Temperature in tenths of degrees. Units are given by temperatureUnits field in deviceInfo""",
        }, # column
        "dewPointSensorHumidity" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.6.1.6",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "100"
                    },
                },
            },
            "access" : "readonly",
            "units" : "%",
            "description" :
                """Humidity reading""",
        }, # column
        "dewPointSensorDewPoint" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.6.1.7",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "-40",
                        "max" : "200"
                    },
                    ],
                    "range" : {
                        "min" : "-40",
                        "max" : "200"
                    },
                },
            },
            "access" : "readonly",
            "units" : "0.1 Degrees",
            "description" :
                """Current reading for Dew-point in tenths of degrees. Units are given by temperatureUnits field in deviceInfo""",
        }, # column
        "ccatSensorTable" : {
            "nodetype" : "table",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.7",
            "status" : "current",
            "description" :
                """Remote CCAT sensor""",
        }, # table
        "ccatSensorEntry" : {
            "nodetype" : "row",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.7.1",
            "status" : "current",
            "linkage" : [
                "ccatSensorIndex",
            ],
            "description" :
                """Entry in the ccatSensorTable table: each entry contains an index and other sensor details""",
        }, # row
        "ccatSensorIndex" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.7.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "100"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Table entry index value""",
        }, # column
        "ccatSensorSerial" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.7.1.2",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Serial Number""",
        }, # column
        "ccatSensorName" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.7.1.3",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Friendly Name""",
        }, # column
        "ccatSensorAvail" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.7.1.4",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Is device currently plugged in?""",
        }, # column
        "ccatSensorValue" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.7.1.5",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "-100",
                        "max" : "5000"
                    },
                    ],
                    "range" : {
                        "min" : "-100",
                        "max" : "5000"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """CCAT sensor reading""",
        }, # column
        "ccatSensorType" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.7.1.6",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """CCAT sensor type""",
        }, # column
        "ccatSensorDescription" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.7.1.7",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """CCAT sensor value description""",
        }, # column
        "t3hdSensorTable" : {
            "nodetype" : "table",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.8",
            "status" : "current",
            "description" :
                """Remote Temperature x 3, Humidity and Dewpoint Sensor""",
        }, # table
        "t3hdSensorEntry" : {
            "nodetype" : "row",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.8.1",
            "status" : "current",
            "linkage" : [
                "t3hdSensorIndex",
            ],
            "description" :
                """Entry in the t3hdSensorTable table: each entry contains an index and other sensor details""",
        }, # row
        "t3hdSensorIndex" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.8.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "100"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Table entry index value""",
        }, # column
        "t3hdSensorSerial" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.8.1.2",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Serial Number""",
        }, # column
        "t3hdSensorName" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.8.1.3",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Friendly Name""",
        }, # column
        "t3hdSensorAvail" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.8.1.4",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Is device currently plugged in?""",
        }, # column
        "t3hdSensorIntName" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.8.1.5",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """T3HD Sensor Internal Friendly Name""",
        }, # column
        "t3hdSensorIntTemp" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.8.1.6",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "-40",
                        "max" : "200"
                    },
                    ],
                    "range" : {
                        "min" : "-40",
                        "max" : "200"
                    },
                },
            },
            "access" : "readonly",
            "units" : "0.1 Degrees",
            "description" :
                """Current reading for Internal Temperature in 0.1 degrees. Units are given by temperatureUnits field in deviceInfo""",
        }, # column
        "t3hdSensorIntHumidity" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.8.1.7",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "100"
                    },
                },
            },
            "access" : "readonly",
            "units" : "%",
            "description" :
                """T3HD Sensor Internal Humidity""",
        }, # column
        "t3hdSensorIntDewPoint" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.8.1.8",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "-40",
                        "max" : "200"
                    },
                    ],
                    "range" : {
                        "min" : "-40",
                        "max" : "200"
                    },
                },
            },
            "access" : "readonly",
            "units" : "0.1 Degrees",
            "description" :
                """Current reading for Internal DewPoint in 0.1 degrees. Units are given by temperatureUnits field in deviceInfo""",
        }, # column
        "t3hdSensorExtAAvail" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.8.1.9",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """T3HD External A status: 0 = unplugged, 1 = normal operation, 2 = device error""",
        }, # column
        "t3hdSensorExtAName" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.8.1.10",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """T3HD External A Friendly Name""",
        }, # column
        "t3hdSensorExtATemp" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.8.1.11",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "-40",
                        "max" : "200"
                    },
                    ],
                    "range" : {
                        "min" : "-40",
                        "max" : "200"
                    },
                },
            },
            "access" : "readonly",
            "units" : "0.1 Degrees",
            "description" :
                """Current reading for External Temperature A in 0.1 degrees. Units are given by temperatureUnits field in deviceInfo""",
        }, # column
        "t3hdSensorExtBAvail" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.8.1.12",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """T3HD External B status: 0 = unplugged, 1 = normal operation, 2 = device error""",
        }, # column
        "t3hdSensorExtBName" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.8.1.13",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """T3HD External B Friendly Name""",
        }, # column
        "t3hdSensorExtBTemp" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.8.1.14",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "-40",
                        "max" : "200"
                    },
                    ],
                    "range" : {
                        "min" : "-40",
                        "max" : "200"
                    },
                },
            },
            "access" : "readonly",
            "units" : "0.1 Degrees",
            "description" :
                """Current reading for External Temperature B in 0.1 degrees. Units are given by temperatureUnits field in deviceInfo""",
        }, # column
        "thdSensorTable" : {
            "nodetype" : "table",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.9",
            "status" : "current",
            "description" :
                """Remote Temperature, Humidity and Dewpoint Sensor""",
        }, # table
        "thdSensorEntry" : {
            "nodetype" : "row",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.9.1",
            "status" : "current",
            "linkage" : [
                "thdSensorIndex",
            ],
            "description" :
                """Entry in the thdSensorTable table: each entry contains an index and other sensor details""",
        }, # row
        "thdSensorIndex" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.9.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "100"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Table entry index value""",
        }, # column
        "thdSensorSerial" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.9.1.2",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Serial Number""",
        }, # column
        "thdSensorName" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.9.1.3",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Friendly Name""",
        }, # column
        "thdSensorAvail" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.9.1.4",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Is device currently plugged in?""",
        }, # column
        "thdSensorTemp" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.9.1.5",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "-40",
                        "max" : "200"
                    },
                    ],
                    "range" : {
                        "min" : "-40",
                        "max" : "200"
                    },
                },
            },
            "access" : "readonly",
            "units" : "0.1 Degrees",
            "description" :
                """Current reading for Temperature in 0.1 degrees. Units are given by temperatureUnits field in deviceInfo""",
        }, # column
        "thdSensorHumidity" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.9.1.6",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "0",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "0",
                        "max" : "100"
                    },
                },
            },
            "access" : "readonly",
            "units" : "%",
            "description" :
                """THD Sensor Humidity""",
        }, # column
        "thdSensorDewPoint" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.9.1.7",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "-40",
                        "max" : "200"
                    },
                    ],
                    "range" : {
                        "min" : "-40",
                        "max" : "200"
                    },
                },
            },
            "access" : "readonly",
            "units" : "0.1 Degrees",
            "description" :
                """Current reading for DewPoint in 0.1 degrees. Units are given by temperatureUnits field in deviceInfo""",
        }, # column
        "rpmSensorTable" : {
            "nodetype" : "table",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.10",
            "status" : "current",
            "description" :
                """Remote Power Manager Sensor""",
        }, # table
        "rpmSensorEntry" : {
            "nodetype" : "row",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.10.1",
            "status" : "current",
            "linkage" : [
                "rpmSensorIndex",
            ],
            "description" :
                """Entry in the rpmSensorTable table: each entry contains an index and other sensor details""",
        }, # row
        "rpmSensorIndex" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.10.1.1",
            "status" : "current",
            "syntax" : {
                "type" :                 {
                    "basetype" : "Integer32",
                    "ranges" : [
                    {
                        "min" : "1",
                        "max" : "100"
                    },
                    ],
                    "range" : {
                        "min" : "1",
                        "max" : "100"
                    },
                },
            },
            "access" : "readonly",
            "description" :
                """Table entry index value""",
        }, # column
        "rpmSensorSerial" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.10.1.2",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Serial Number""",
        }, # column
        "rpmSensorName" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.10.1.3",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Friendly Name""",
        }, # column
        "rpmSensorAvail" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.10.1.4",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """Is device currently plugged in?""",
        }, # column
        "rpmSensorEnergy" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.10.1.5",
            "status" : "current",
            "access" : "readonly",
            "units" : "kWh",
            "description" :
                """RPM Sensor Accumulated Energy""",
        }, # column
        "rpmSensorVoltage" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.10.1.6",
            "status" : "current",
            "access" : "readonly",
            "units" : "Volts (rms)",
            "description" :
                """RPM Sensor Voltage""",
        }, # column
        "rpmSensorVoltageMax" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.10.1.7",
            "status" : "current",
            "access" : "readonly",
            "units" : "Volts (rms)",
            "description" :
                """RPM Sensor Voltage (Max)""",
        }, # column
        "rpmSensorVoltageMin" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.10.1.8",
            "status" : "current",
            "access" : "readonly",
            "units" : "Volts (rms)",
            "description" :
                """RPM Sensor Voltage (Min)""",
        }, # column
        "rpmSensorVoltagePeak" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.10.1.9",
            "status" : "current",
            "access" : "readonly",
            "units" : "Volts",
            "description" :
                """RPM Sensor Voltage (Peak)""",
        }, # column
        "rpmSensorCurrent" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.10.1.10",
            "status" : "current",
            "access" : "readonly",
            "units" : "0.1 Amps (rms)",
            "description" :
                """RPM Sensor Current reading in deciAmps""",
        }, # column
        "rpmSensorRealPower" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.10.1.11",
            "status" : "current",
            "access" : "readonly",
            "units" : "Watts",
            "description" :
                """RPM Sensor Real Power""",
        }, # column
        "rpmSensorApparentPower" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.10.1.12",
            "status" : "current",
            "access" : "readonly",
            "units" : "Volt-Amps",
            "description" :
                """RPM Sensor Apparent Power""",
        }, # column
        "rpmSensorPowerFactor" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.10.1.13",
            "status" : "current",
            "access" : "readonly",
            "units" : "%",
            "description" :
                """RPM Sensor Power Factor""",
        }, # column
        "rpmSensorOutlet1" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.10.1.14",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """RPM Sensor Outlet 1 State: 0 = off, 1 = on""",
        }, # column
        "rpmSensorOutlet2" : {
            "nodetype" : "column",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.10.1.15",
            "status" : "current",
            "access" : "readonly",
            "description" :
                """RPM Sensor Outlet 2 State: 0 = off, 1 = on""",
        }, # column
        "trap" : {
            "nodetype" : "node",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767",
        }, # node
        "trapPrefix" : {
            "nodetype" : "node",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0",
        }, # node
    }, # nodes

    "notifications" : {
        "internalTestNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.10101",
            "status" : "current",
            "objects" : {
            },
            "description" :
                """Test SNMP Trap""",
        }, # notification
        "internalTempNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.10205",
            "status" : "current",
            "objects" : {
                "internalTemp" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "temperatureUnits" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """Internal Temperature Sensor Trap""",
        }, # notification
        "internalHumidityNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.10206",
            "status" : "current",
            "objects" : {
                "internalHumidity" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """Humidity reading Trap""",
        }, # notification
        "internalDewPointNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.10207",
            "status" : "current",
            "objects" : {
                "internalDewPoint" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "temperatureUnits" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """Internal Dew Point Sensor Trap""",
        }, # notification
        "internalIO1NOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.10208",
            "status" : "current",
            "objects" : {
                "internalIO1" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """Current reading for Analog Input 1 Trap""",
        }, # notification
        "internalIO2NOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.10209",
            "status" : "current",
            "objects" : {
                "internalIO2" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """Current reading for Analog Input 2 Trap""",
        }, # notification
        "internalIO3NOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.10210",
            "status" : "current",
            "objects" : {
                "internalIO3" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """Current reading for Analog Input 3 Trap""",
        }, # notification
        "internalIO4NOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.10211",
            "status" : "current",
            "objects" : {
                "internalIO4" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """Current reading for Analog Input 4 Trap""",
        }, # notification
        "tempSensorTempNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.10405",
            "status" : "current",
            "objects" : {
                "tempSensorTemp" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "temperatureUnits" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """Remote Temperature Sensor Trap""",
        }, # notification
        "airFlowSensorTempNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.10505",
            "status" : "current",
            "objects" : {
                "airFlowSensorTemp" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "temperatureUnits" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """AFHT3 Sensor Temperature Trap""",
        }, # notification
        "airFlowSensorFlowNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.10506",
            "status" : "current",
            "objects" : {
                "airFlowSensorFlow" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """AFHT3 Airflow reading Trap""",
        }, # notification
        "airFlowSensorHumidityNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.10507",
            "status" : "current",
            "objects" : {
                "airFlowSensorHumidity" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """AFHT3 Humidity reading Trap""",
        }, # notification
        "airFlowSensorDewPointNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.10508",
            "status" : "current",
            "objects" : {
                "airFlowSensorDewPoint" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "temperatureUnits" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """AFHT3 Sensor Dew Point Trap""",
        }, # notification
        "dewPointSensorTempNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.10605",
            "status" : "current",
            "objects" : {
                "dewPointSensorTemp" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "temperatureUnits" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """Remote Dew Point Sensor Temperature Trap""",
        }, # notification
        "dewPointSensorHumidityNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.10606",
            "status" : "current",
            "objects" : {
                "dewPointSensorHumidity" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """Humidity reading Trap""",
        }, # notification
        "dewPointSensorDewPointNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.10607",
            "status" : "current",
            "objects" : {
                "dewPointSensorDewPoint" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "temperatureUnits" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """Remote Dew Point Sensor Dew Point Trap""",
        }, # notification
        "ccatSensorValueNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.10705",
            "status" : "current",
            "objects" : {
                "ccatSensorValue" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "ccatSensorType" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """CCAT sensor reading Trap""",
        }, # notification
        "t3hdSensorIntTempNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.10806",
            "status" : "current",
            "objects" : {
                "t3hdSensorIntTemp" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "temperatureUnits" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """T3HD Sensor Temperature Trap""",
        }, # notification
        "t3hdSensorIntHumidityNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.10807",
            "status" : "current",
            "objects" : {
                "t3hdSensorIntHumidity" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """T3HD Sensor Internal Humidity Trap""",
        }, # notification
        "t3hdSensorIntDewPointNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.10808",
            "status" : "current",
            "objects" : {
                "t3hdSensorIntDewPoint" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "temperatureUnits" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """T3HD Sensor Dew Point Trap""",
        }, # notification
        "t3hdSensorExtATempNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.10811",
            "status" : "current",
            "objects" : {
                "t3hdSensorExtATemp" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "temperatureUnits" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """T3HD Sensor External A Temperature Trap""",
        }, # notification
        "t3hdSensorExtBTempNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.10814",
            "status" : "current",
            "objects" : {
                "t3hdSensorExtBTemp" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "temperatureUnits" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """T3HD Sensor External B Temperature Trap""",
        }, # notification
        "thdSensorTempNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.10905",
            "status" : "current",
            "objects" : {
                "thdSensorTemp" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "temperatureUnits" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """THD Sensor Temperature Trap""",
        }, # notification
        "thdSensorHumidityNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.10906",
            "status" : "current",
            "objects" : {
                "thdSensorHumidity" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """THD Sensor Humidity Trap""",
        }, # notification
        "thdSensorDewPointNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.10907",
            "status" : "current",
            "objects" : {
                "thdSensorDewPoint" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "temperatureUnits" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """THD Sensor Dew Point Trap""",
        }, # notification
        "rpmSensorEnergyNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.11005",
            "status" : "current",
            "objects" : {
                "rpmSensorEnergy" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """RPM Sensor Accumulated Energy Trap""",
        }, # notification
        "rpmSensorVoltageNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.11006",
            "status" : "current",
            "objects" : {
                "rpmSensorVoltage" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """RPM Sensor Voltage Trap""",
        }, # notification
        "rpmSensorVoltageMaxNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.11007",
            "status" : "current",
            "objects" : {
                "rpmSensorVoltageMax" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """RPM Sensor Voltage (Max) Trap""",
        }, # notification
        "rpmSensorVoltageMinNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.11008",
            "status" : "current",
            "objects" : {
                "rpmSensorVoltageMin" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """RPM Sensor Voltage (Min) Trap""",
        }, # notification
        "rpmSensorVoltagePeakNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.11009",
            "status" : "current",
            "objects" : {
                "rpmSensorVoltagePeak" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """RPM Sensor Voltage (Peak) Trap""",
        }, # notification
        "rpmSensorCurrentNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.11010",
            "status" : "current",
            "objects" : {
                "rpmSensorCurrent" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """RPM Sensor Current Trap""",
        }, # notification
        "rpmSensorRealPowerNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.11011",
            "status" : "current",
            "objects" : {
                "rpmSensorRealPower" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """RPM Sensor Real Power Trap""",
        }, # notification
        "rpmSensorApparentPowerNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.11012",
            "status" : "current",
            "objects" : {
                "rpmSensorApparentPower" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """RPM Sensor Apparent Power Trap""",
        }, # notification
        "rpmSensorPowerFactorNOTIFY" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.11013",
            "status" : "current",
            "objects" : {
                "rpmSensorPowerFactor" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """RPM Sensor Power Factor Trap""",
        }, # notification
        "internalTempCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.20205",
            "status" : "current",
            "objects" : {
                "internalTemp" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "temperatureUnits" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """Internal Temperature Sensor Clear Trap""",
        }, # notification
        "internalHumidityCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.20206",
            "status" : "current",
            "objects" : {
                "internalHumidity" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """Humidity reading Clear Trap""",
        }, # notification
        "internalDewPointCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.20207",
            "status" : "current",
            "objects" : {
                "internalDewPoint" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "temperatureUnits" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """Internal Dew Point Sensor Clear Trap""",
        }, # notification
        "internalIO1CLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.20208",
            "status" : "current",
            "objects" : {
                "internalIO1" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """Current reading for Analog Input 1 Clear Trap""",
        }, # notification
        "internalIO2CLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.20209",
            "status" : "current",
            "objects" : {
                "internalIO2" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """Current reading for Analog Input 2 Clear Trap""",
        }, # notification
        "internalIO3CLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.20210",
            "status" : "current",
            "objects" : {
                "internalIO3" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """Current reading for Analog Input 3 Clear Trap""",
        }, # notification
        "internalIO4CLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.20211",
            "status" : "current",
            "objects" : {
                "internalIO4" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """Current reading for Analog Input 4 Clear Trap""",
        }, # notification
        "tempSensorTempCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.20405",
            "status" : "current",
            "objects" : {
                "tempSensorTemp" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "temperatureUnits" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """Remote Temperature Sensor Clear Trap""",
        }, # notification
        "airFlowSensorTempCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.20505",
            "status" : "current",
            "objects" : {
                "airFlowSensorTemp" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "temperatureUnits" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """AFHT3 Sensor Temperature Clear Trap""",
        }, # notification
        "airFlowSensorFlowCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.20506",
            "status" : "current",
            "objects" : {
                "airFlowSensorFlow" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """AFHT3 Airflow reading Clear Trap""",
        }, # notification
        "airFlowSensorHumidityCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.20507",
            "status" : "current",
            "objects" : {
                "airFlowSensorHumidity" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """AFHT3 Humidity reading Clear Trap""",
        }, # notification
        "airFlowSensorDewPointCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.20508",
            "status" : "current",
            "objects" : {
                "airFlowSensorDewPoint" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "temperatureUnits" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """AFHT3 Sensor Dew Point Clear Trap""",
        }, # notification
        "dewPointSensorTempCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.20605",
            "status" : "current",
            "objects" : {
                "dewPointSensorTemp" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "temperatureUnits" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """Remote Dew Point Sensor Temperature Clear Trap""",
        }, # notification
        "dewPointSensorHumidityCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.20606",
            "status" : "current",
            "objects" : {
                "dewPointSensorHumidity" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """Humidity reading Clear Trap""",
        }, # notification
        "dewPointSensorDewPointCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.20607",
            "status" : "current",
            "objects" : {
                "dewPointSensorDewPoint" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "temperatureUnits" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """Remote Dew Point Sensor Dew Point Clear Trap""",
        }, # notification
        "ccatSensorValueCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.20705",
            "status" : "current",
            "objects" : {
                "ccatSensorValue" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "ccatSensorType" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """CCAT sensor reading Clear Trap""",
        }, # notification
        "t3hdSensorIntTempCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.20806",
            "status" : "current",
            "objects" : {
                "t3hdSensorIntTemp" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "temperatureUnits" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """T3HD Sensor Temperature Clear Trap""",
        }, # notification
        "t3hdSensorIntHumidityCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.20807",
            "status" : "current",
            "objects" : {
                "t3hdSensorIntHumidity" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """T3HD Sensor Internal Humidity Clear Trap""",
        }, # notification
        "t3hdSensorIntDewPointCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.20808",
            "status" : "current",
            "objects" : {
                "t3hdSensorIntDewPoint" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "temperatureUnits" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """T3HD Sensor Dew Point Clear Trap""",
        }, # notification
        "t3hdSensorExtATempCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.20811",
            "status" : "current",
            "objects" : {
                "t3hdSensorExtATemp" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "temperatureUnits" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """T3HD Sensor External A Temperature Clear Trap""",
        }, # notification
        "t3hdSensorExtBTempCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.20814",
            "status" : "current",
            "objects" : {
                "t3hdSensorExtBTemp" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "temperatureUnits" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """T3HD Sensor External B Temperature Clear Trap""",
        }, # notification
        "thdSensorTempCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.20905",
            "status" : "current",
            "objects" : {
                "thdSensorTemp" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "temperatureUnits" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """THD Sensor Temperature Clear Trap""",
        }, # notification
        "thdSensorHumidityCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.20906",
            "status" : "current",
            "objects" : {
                "thdSensorHumidity" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """THD Sensor Humidity Clear Trap""",
        }, # notification
        "thdSensorDewPointCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.20907",
            "status" : "current",
            "objects" : {
                "thdSensorDewPoint" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
                "temperatureUnits" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """THD Sensor Dew Point Clear Trap""",
        }, # notification
        "rpmSensorEnergyCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.21005",
            "status" : "current",
            "objects" : {
                "rpmSensorEnergy" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """RPM Sensor Accumulated Energy Clear Trap""",
        }, # notification
        "rpmSensorVoltageCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.21006",
            "status" : "current",
            "objects" : {
                "rpmSensorVoltage" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """RPM Sensor Voltage Clear Trap""",
        }, # notification
        "rpmSensorVoltageMaxCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.21007",
            "status" : "current",
            "objects" : {
                "rpmSensorVoltageMax" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """RPM Sensor Voltage (Max) Clear Trap""",
        }, # notification
        "rpmSensorVoltageMinCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.21008",
            "status" : "current",
            "objects" : {
                "rpmSensorVoltageMin" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """RPM Sensor Voltage (Min) Clear Trap""",
        }, # notification
        "rpmSensorVoltagePeakCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.21009",
            "status" : "current",
            "objects" : {
                "rpmSensorVoltagePeak" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """RPM Sensor Voltage (Peak) Clear Trap""",
        }, # notification
        "rpmSensorCurrentCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.21010",
            "status" : "current",
            "objects" : {
                "rpmSensorCurrent" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """RPM Sensor Current Clear Trap""",
        }, # notification
        "rpmSensorRealPowerCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.21011",
            "status" : "current",
            "objects" : {
                "rpmSensorRealPower" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """RPM Sensor Real Power Clear Trap""",
        }, # notification
        "rpmSensorApparentPowerCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.21012",
            "status" : "current",
            "objects" : {
                "rpmSensorApparentPower" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """RPM Sensor Apparent Power Clear Trap""",
        }, # notification
        "rpmSensorPowerFactorCLEAR" : {
            "nodetype" : "notification",
            "moduleName" : "IT-WATCHDOGS-V4-MIB",
            "oid" : "1.3.6.1.4.1.17373.4.1.32767.0.21013",
            "status" : "current",
            "objects" : {
                "rpmSensorPowerFactor" : {
                    "nodetype" : "object",
                    "module" : "IT-WATCHDOGS-V4-MIB"
                },
            },
            "description" :
                """RPM Sensor Power Factor Clear Trap""",
        }, # notification
    }, # notifications

}
