  <h1>
    <center>
      <font color=#000066>
        navAdmin - Main menu
      </font>
    </center>
  </h1>

  <center>
    <table border="0">
<!--
      <tr>
        <td>
          <a href="[/link.vp]">vlanPlot config</a>
        </td>
        <td>
          Konfigurasjon av vlanPlot
        </td>
      </tr>
-->
      <tr>
        <td>
          <!-- <a href="[/link.topologivisning]">Topologivisning</a> -->
          Topologivisning
        </td>
        <td>
          Se topologien i tre-struktur
        </td>
      </tr>
      <tr>
        <td>
          <a href="[/link.ni]">Rapporter</a>
        </td>
        <td>
          Se rapporter fra nattlig kj&oslash;ring av navAdmin-funksjoner.
        </td>
      </tr>
<!--
      <tr>
        <td>
          <a href="[/link.vp.showconfig]">Vis db</a>
        </td>
        <td>
          Vis config-databasen
        </td>
      </tr>
-->
    </table>
  </center>
