#!/usr/bin/env python
# Start the ipdevpoll daemon
# But first, make sure this daemon is using pysnmp-se (v3 API)
import os
os.environ['PYSNMP_API_VERSION'] = 'v3'

from nav.ipdevpoll.daemon import *

if __name__ == '__main__':
    main()
