<table width=100% bgcolor=#000000 border=0 cellpadding=0 cellspacing=1>
 <tr><td>
   <table width=100% cellspacing=1 border=0 cellpadding=2 bgcolor=#e6e6e6>
   <tr><td bgcolor=#486591><font color=#ffffff>
        <strong><font color=#fefefe>NAV
</font></strong></font>
       </td>
   </tr>
   </table>
   <table width=100% cellspacing=1 border=0 cellpadding=7 bgcolor=#fefefe>
   <tr><td bgcolor=#e6e6e6>

<b>
<a href="/">NAV hovedside</a><p>
<A HREF="/vlanPlot/">Nettkart</A><p>
<a href="/status/">Status n†</a><p>
<a href="http://www.nav.ntnu.no/NAVlinks/">Om NAV / Andre NAV</a><p>

</b>


       </td>
   </tr>
   </table>
  </td>
 </tr>
</table>
<p>

<table width=100% bgcolor=#000000 border=0 cellpadding=0 cellspacing=1>
 <tr><td>
   <table width=100% cellspacing=1 border=0 cellpadding=2 bgcolor=#e6e6e6>
   <tr><td bgcolor=#486591><font color=#ffffff>
        <strong><font color=#fefefe>Brukerinfo
<a href=https://bb.itea.ntnu.no/>Logg inn</a>
<a href=/doc/hjelp.html>Hjelp</a>
</font></strong></font>
       </td>
   </tr>
   </table>
   <table width=100% cellspacing=1 border=0 cellpadding=7 bgcolor=#fefefe>
   <tr><td bgcolor=#e6e6e6>
         <table>
         <tr><td><b>BRUKER:</td><td>kristian</td></tr>
         <tr><td><b>ADGANG:</td><td>N/A</td></tr>
         </table><p>
       </td>
   </tr>
   </table>
  </td>
 </tr>
</table>
<p>
</td></tr></table></td></tr></table></td><td valign=top bgcolor=#ffffff><table border=0 cellpadding=10 cellspacing=1> <tr><td>