#!/usr/bin/perl
# Dette programmet går gjennom alle svitsjeportene,
# ruter-interfacene, svitsj-bakplanene og ruter-cpuene,
# finner lasten de har hatt i løpet av det spesifiserte
# tidsrommet. Hvis lasten overskrider en oppgitt grense,
# sender programmet en hysterese-trap vha. snmp.
#
# Skrevet av John Magne Bredal
# 29.09.2000
# 
# 23.01.2001 - scriptet bruker nå de nye navnene på 
# tabellene i databasen. JM
#
# 26.01.2001 - lagd en ny sub-oid som identifiserer hvilken
# enhet som det er for stor belastning på. Dette fordi det er 
# bedre at dette scriptet gjør det, enn at TrapDetect gjør det.
#
# 02-02-2001 - Sender med nettelid for de ulike enhetene - JM
############################################################

use Pg;
use strict;
use RRDs;
use Mail::Mailer;
use SNMP_util;

# "Globale" variable
# Hvor stor belastning den skal kicke på (i prosent).
my $limit = 87;

# Tidsrom (i sekunder bakover i tid)
my $fra = -900;

# SNMP-variable
my $ipadresse = "129.241.190.201";
my $hostname = "bb";
my $prefix = '.1.3.6.1.4.1.3001.1.3';

my $fil = "/usr/local/nav/local/log/alarm";
my $enhet = "/usr/local/nav/local/log/alarm2";
my $to = "bredal\@stud.ntnu.no";
my %svitsjliste;
my %ruterliste;

my $cricketpath = "/home/navcron/cricket";

my $dbh = &db_connect();

# Kjører subrutinene
#print "\t----- Start -> Switches -----\n\n";
&switches;
#print "\t\n\n----- End of Switches -> Routers  -----\n\n";
&routers;
#print "\t\n\n----- End of Routers -> Switch-ports -----\n\n";
&switchports;
#print "\t\n\n----- End of Switch-ports -> Router-interfaces -----\n";
&routerinterfaces;

sub switches {

    my ($id, $sysname);

    # Henter ut alle svitsjer og svitsjeporter
    my $hentsvitsjer = &db_select("SELECT boksid,sysName FROM boks WHERE kat='SW' ORDER BY sysName",$dbh);

    while (($id, $sysname) = $hentsvitsjer->fetchrow) {
	$id = lc $id;
	$sysname = lc $sysname;
	$svitsjliste{$id} = $sysname;
    }

    while (($id, $sysname) = each %svitsjliste) {
	my $verdi = 0;
	if (-e "$cricketpath/cricket-data/switches/$sysname.rrd") {
	    my $RRD = "$cricketpath/cricket-data/switches/$sysname.rrd";

	    my($graphret) = RRDs::graph "/dev/null",
	    "--start","$fra",
	    "--end","now",
	    "DEF:value=$RRD:ds0:AVERAGE", # Backplane
	    "PRINT:value:AVERAGE:%6.2lf";
	    my($ERROR) = RRDs::error;
	    warn "ERROR: $ERROR\n" if $ERROR ;
	    
	    if (@$graphret[0] =~ /\d/) { $verdi = int(@$graphret[0]); } else { $verdi = 0; }

	    # Skriver ut data til skjerm
	    #print "$sysname:\t$verdi\n";

	} else {
	    #print "Finner ikke $sysname.rrd\n";
	}
    }

}

sub routers {

    my ($id,$sysname);

    my $hentrutere = &db_select("SELECT boksid,sysName FROM boks WHERE kat='GW'",$dbh);

    while (($id, $sysname) = $hentrutere->fetchrow) {
	    $ruterliste{$id} = $sysname;
    }

    while (($id, $sysname) = each %ruterliste) {
	my $verdi;
	if (-e "$cricketpath/cricket-data/routers/$sysname.rrd") {
	    my $RRD = "$cricketpath/cricket-data/routers/$sysname.rrd";

	    my($graphret) = RRDs::graph "/dev/null",
	    "--start","$fra",
	    "--end","now",
	    "DEF:value=$RRD:ds1:AVERAGE", # avg5min
	    "PRINT:value:AVERAGE:%6.2lf";
	    my($ERROR) = RRDs::error;
	    warn "ERROR: $ERROR\n" if $ERROR ;
	    
	    if (@$graphret[0] =~ /\d/) { $verdi = int(@$graphret[0]); } else { $verdi = 0; }

	    #print "$sysname:\t$verdi\n";

	    # Sender melding hvis belastning over godkjent.
	    if ($verdi > $limit && $verdi < 100) {
		# Sjekker om finnes fra før
		unless(&sjekkfil2($sysname)) {
		    #print "$sysname:\t$verdi\n";
		    # Skriver til oversiktsfil
		    open (ENHET, ">>$enhet") or die "Kunne ikke legge til $enhet $! \n";
		    print ENHET "$sysname\n";
		    close ENHET;
		    
		    &sendtrap2($sysname, $id, "$verdi%");
		} else {
		    #print "Innlegg finnes fra før\n";
		}
	    }
	} else {
	    #print "Kan ikke finne $sysname.rrd\n";
	}
    }

}

sub switchports {

    my ($id, $sysname);

    while (($id, $sysname) = each %svitsjliste) {
	my $sporring = "SELECT modul,port,speed FROM swport WHERE boksid=$id AND status='up' AND speed!=''";
	#print "$sporring\n";
	my $hentporter = &db_select($sporring,$dbh);

	while (my ($modul,$port,$speed) = $hentporter->fetchrow) {
	    # Diverse omformateringer på filnavnene... :(
	    my $org_modul = $modul;
	    $modul = lc $modul;
	    $modul =~ s/fe/fa/;
	    $modul =~ s/ge/gi/;
	    my $mp = $modul."_".$port;
	    my $org_mp = $org_modul."_".$port;

	    my $path = $cricketpath;
	    if ($speed == 1000) {
		$path .= "/cricket-data/giga-switch-ports";
	    } else {
		$path .= "/cricket-data/switch-ports";
	    }

	    my $verdi;
	    if (-e "$path/$sysname/$mp.rrd") {
		my $RRD = "$path/$sysname/$mp.rrd";

		my($graphret) = RRDs::graph "/dev/null",
		"--start","$fra",
		"--end","now",
		"DEF:value=$RRD:ds1:AVERAGE", # ifOutOctets
		"PRINT:value:AVERAGE:%6.2lf";
		my($ERROR) = RRDs::error;
		warn "ERROR: $ERROR\n" if $ERROR ;
		
		if (@$graphret[0] =~ /\d/) { $verdi = 8 * int(@$graphret[0]); } else { $verdi = 0; }
		
		if ($speed) {
		    my $mspeed = $speed * 10486;
		    my $belastning = $verdi/$mspeed;
		    $belastning =~ m/\d+\.(\d)/;
		    my $rest = $1;
		    if ($rest > 4) {
			$belastning += 1;
		    }

		    $belastning = int($belastning);
		    #print "$sysname/$mp:\t$belastning\n";
		    
		    # Skriver ut interessant info
		    if ($belastning > $limit && $belastning < 100) {

			# Hvis ikke innlegg finnes fra før
			# legg inn i fil, sende mail.
			unless (&sjekkfil($sysname,$org_mp)) {
			    #print "Innlegg ikke funnet\n";

			    # Sender mail hvis belastning er for stor.
			    my $body = "port: $sysname/$org_mp\n";
			    $body .= "nettelid: $id\n";
			    $body .= "last: $belastning%\n";
			    #print $body;

			    open (FIL, ">>$fil") or die "Kunne ikke åpne $fil $!\n";
			    print FIL "$sysname,$org_mp\n";
			    close FIL;
			    
			    # Sender trap
			    my $temp1 = "$sysname/$org_mp";
			    &sendtrap($temp1, $id,"$belastning%");

			    #print $body;
			    #&sendmail($body);
			} else {
			    #print "Innlegg funnet!\n";
			}
		    }
		    if ($belastning > 100) {
			my $body = "port: $sysname/$mp\n";
			$body .= "last: $belastning%\n";
#			    &sendmail($body);
		    }
		}
	    } else {
		#print "Finner ikke $path/$sysname/$mp\n";
	    }
	}
    }
} #sub switchports


sub routerinterfaces{

    my ($id,$sysname);

    while (($id,$sysname) = each %ruterliste) {
	my $hentporter = &db_select("SELECT g.interf,g.speed FROM gwport g WHERE g.boksid=$id AND g.masterindex is null AND g.interf not like 'Tunnel%'",$dbh);

	while (my ($interf, $speed) = $hentporter->fetchrow) {
	    unless ($interf =~ /Loopback0/) {
		# Omforming på filnavn
		my $org_interf = $interf;
		$interf = lc $interf;
		$interf =~ s(/)(_)g;
		
		my $path = $cricketpath;
		if ($speed == 1000) {
		    $path .= "/cricket-data/giga-router-interfaces";
		} else {
		    $path .= "/cricket-data/router-interfaces";
		}

		# Henter lastdata
		my $verdi;
		if (-e "$path/$sysname/$interf.rrd") {
		    my $RRD = "$path/$sysname/$interf.rrd";

		    my($graphret) = RRDs::graph "/dev/null",
		    "--start","$fra",
		    "--end","now",
		    "DEF:value=$RRD:ds1:AVERAGE", # ifOutOctets
		    "PRINT:value:AVERAGE:%6.2lf";
		    my($ERROR) = RRDs::error;
		    warn "ERROR: $ERROR\n" if $ERROR ;
		    
		    if (@$graphret[0] =~ /\d/) { $verdi = 8 * int(@$graphret[0]); } else { $verdi = 0; }

		    if ($speed) {
			my $mspeed = $speed * 10486;
			my $belastning = $verdi/$mspeed;
			$belastning =~ m/\d+\.(\d)/;
			my $rest = $1;
			if ($rest > 4) {
			    $belastning += 1;
			}

			$belastning = int($belastning);
			#print "$sysname/$interf:\t$belastning\n";
			
			# Skriver ut interessant info
			if ($belastning > $limit && $belastning < 100) {
			    # Hvis ikke innlegg finnes fra før
			    # legg inn i fil, sende mail.
			    unless (&sjekkfil($sysname,$org_interf)) {
				#print "Innlegg ikke funnet\n";

				open (FIL, ">>$fil") or die "Kunne ikke åpne $fil $!\n";
				print FIL "$sysname,$org_interf\n";
				close FIL;

				# Sender trap
				my $temp1 = "$sysname/$org_interf";
				&sendtrap($temp1, $id, "$belastning%");
				
				# Sender mail.
				my $body = "port: $sysname/$org_interf\n";
				$body .= "nettelid: $id\n";
				$body .= "last: $belastning%\n";
				
				#print "$body\n";
				#&sendmail($body);
			    } else {
				#print "Innlegg funnet!\n";
			    }
			}
		    }
		} else {
		    #print "Finner ikke $sysname: $interf.rrd\n\n";
		}
	    }
	}
    }
}

sub sendmail {

    my $body = shift;
    my $subject = "hystereseAlarmOn";

    #print "Sendmail: $body\n";
    my $from = "bredal";

    my $mailer = Mail::Mailer->new();
    $mailer->open({ From    => $from,
		    To      => $to,
		    Subject => $subject,
		})
	or die "Can't open: $!\n";
    print $mailer $body;
    $mailer->close();

}

sub sjekkfil {

    my ($sysname, $port) = @_;
    my $funnet = 0;
    
    open (FIL, $fil) or die "Kunne ikke åpne $fil for lesing $!\n";
    while (<FIL>) {
	if (m/$sysname/i && m/$port/i) {
	    $funnet = 1;
	}
    }
    close FIL;

    return $funnet;
}

sub sjekkfil2 {

    my $sysname = shift;
    my $funnet = 0;
    
    open (FIL, $enhet) or die "Kunne ikke åpne $enhet for lesing $!\n";
    while (<FIL>) {
	if (m/$sysname/i) {
	    $funnet = 1;
	}
    }
    close FIL;

    return $funnet;
}

sub sendtrap {
    
    my ($sysname, $nettelid, $belastning) = @_;
    my @data;

    my $string = "ifInOctets:hysteresis:8750000:10000000";

    my $newprefix = ".1.3.6.1.4.1.3001.1.3.1";

    push(@data, "$newprefix.1", 'string', "$string");
    push(@data, "$newprefix.2", 'string', "$nettelid");
    push(@data, "$newprefix.3", 'string', "$sysname");
    push(@data, "$newprefix.4", 'string', "$belastning");

    #&snmptrap($ipadresse, $prefix, $hostname, 6, 1, @data);

}

sub sendtrap2 {

    my ($sysname, $nettelid, $belastning) = @_;
    my @data;

    my $string = "ifInOctets:hysteresis:8750000:10000000";

    my $newprefix = ".1.3.6.1.4.1.3001.1.3.1";

    push(@data, "$newprefix.1", 'string', "$string");
    push(@data, "$newprefix.2", 'string', "$nettelid");
    push(@data, "$newprefix.3", 'string', "$sysname");
    push(@data, "$newprefix.4", 'string', "$belastning");

    #&snmptrap($ipadresse, $prefix, $hostname, 6, 1, @data);
}

sub db_readconf {
    my $dbconf = '/usr/local/nav/local/etc/conf/db.conf';

    open(IN, $dbconf) || die "Could not open $dbconf: $!\n";
    my %hash = map { /\s*(.+?)\s*=\s*(.*?)\s*(\#.*)?$/ && $1 => $2 } 
    grep { !/^(\s*\#|\s+)$/ && /.+=.*/ } <IN>;
    close(IN);

    return %hash;
}

sub db_connect {
    my %dbconf = &db_readconf();

    my $db = $dbconf{db_nav};
    my $user = $dbconf{script_hystereseOn};
    my $pass = $dbconf{'userpw_' . $user};

    my $conn = Pg::connectdb("dbname=$db user=$user password=$pass");
    die $conn->errorMessage unless PGRES_CONNECTION_OK eq $conn->status;
    return $conn;
}

sub db_select {
    my $sql = $_[0];
    my $conn = $_[1];
    my $resultat = $conn->exec($sql);
    print "DATABASEFEIL: $sql\n".$conn->errorMessage
        unless ($resultat->resultStatus eq PGRES_TUPLES_OK);
    return $resultat;
}

sub db_execute {
    my $sql = $_[0];
    my $conn = $_[1];
    my $resultat = $conn->exec($sql);
    print "DATABASEFEIL: $sql\n".$conn->errorMessage
        unless ($resultat->resultStatus eq PGRES_COMMAND_OK);
#die er byttet med print

    return $resultat;
}
