
"""Database wrappers.
Autogenerated by forgetSQL 2003-07-07.
"""

import forgetSQL

class _Wrapper(forgetSQL.Forgetter):
    """Just a simple wrapper class so that you may
    easily change stuff for all forgetters. Typically
    this involves subcliassing MysqlForgetter instead."""

    # Remember to change the class function cursor() so that
    # it returns a cursor connected to the database.
    # 
    ## cursor = lambda: myDatabase.cursor()
    pass



class Account(_Wrapper):
    _sqlFields =  {'ext_sync': 'ext_sync',
                  'id': 'id',
                  'login': 'login',
                  'name': 'name',
                  'password': 'password'}
    _sqlLinks =  {}
    _userClasses =  {}
    _shortView =  ()
    _sqlTable =  'Account'
    _descriptions =  {}

class Accountgroup(_Wrapper):
    _sqlFields =  {'id': 'id', 'descr': 'descr', 'name': 'name'}
    _sqlLinks =  {}
    _userClasses =  {}
    _shortView =  ()
    _sqlTable =  'AccountGroup'
    _descriptions =  {}

class Accountingroup(_Wrapper):
    _sqlFields =  {'account': 'accountid', 'groupid': 'groupid'}
    _sqlLinks =  {}
    _userClasses =  {'account': 'Account'}
    _shortView =  ()
    _sqlTable =  'AccountInGroup'
    _descriptions =  {}

class Accountorg(_Wrapper):
    _sqlFields =  {'account': 'accountid', 'orgid': 'orgid'}
    _sqlLinks =  {}
    _userClasses =  {'account': 'Account'}
    _shortView =  ()
    _sqlTable =  'AccountOrg'
    _descriptions =  {}


# Prepare them all. We need to send in our local
# namespace.
forgetSQL.prepareClasses(locals())

