#!/bin/sh
####################
#
# $Id: alerengine,v 1.0 2003/09/15 12:59:26 arneos Exp $
# This file is part of the NAV project.
# This script controls start/stop/status of the NAV alertEngine Daemon.
#
# Copyright (c) 2002 by NTNU, ITEA nettgruppen
# Authors: Arne Oslebo <arne.oslebo@uninett.no>
#
####################

# Source function library.
. /usr/local/nav/navme/etc/init.d/functions

[ -x /usr/local/nav/navme/subsystem/alertEngine/alertdaemon.pl ] || exit 1

cd /usr/local/nav/navme/subsystem/alertEngine

# See how we were called.
case "$1" in
	start)
		# Start daemons.
		rc=alertdaemon.pl start
		echo
		exit $rc
		;;
	stop)
		# Stop daemons.
		rc=alertdaemon.pl stop
		echo
		exit $rc
        	;;
	restart)
		rc=alertdaemon.pl restart
		echo
		exit $rc
		;;
	status)
		rc=alertdaemon.pl status
		echo
		exit $rc
		;;
	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
esac

exit 0

# === End of File ===
