#!/bin/sh
####################
#
# $Id: eventengine,v 1.1 2003/05/28 15:10:26 kristian Exp $
# This file is part of the NAV project.
# This script controls start/stop/status of the NAV eventEngine Daemon.
#
# Copyright (c) 2002 by NTNU, ITEA nettgruppen
# Authors: Kristian Eide <kreide@online.no>
#          Morten Vold <morten.vold@itea.ntnu.no>
#
####################

# Source function library.
. /usr/local/nav/navme/etc/init.d/functions

[ -x /usr/local/nav/navme/subsystem/eventEngine/eventEngine.sh ] || exit 1

# See how we were called.
case "$1" in
	start)
		# Start daemons.
		echo -n "Starting eventEngine: "
		rc= daemon /usr/local/nav/navme/subsystem/eventEngine/eventEngine.sh
		echo
		exit $rc
		;;
	stop)
		# Stop daemons.
		echo -n "Shutting down eventEngine: "
		if killproc eventEngine; then
		# Make sure the pidfile is gone when stopping normal
		    rm -f /usr/local/nav/local/var/run/eventEngine.pid
		    echo
		    exit 0
		else
		    echo
		    exit 1
		fi
        	;;
	restart)
		$0 stop
		$0 start
		;;
	status)
	        status eventEngine
		exit $?
		;;
	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
esac

exit 0

# === End of File ===
