#!/bin/sh
####################
#
# $Id: smsd,v 1.3 2003/05/26 12:19:36 mortenv Exp $
# This file is part of the NAV project.
# This script controls start/stop/status of the NAV SMS Daemon.
#
# Copyright (c) 2002 by NTNU, ITEA nettgruppen
# Authors: Morten Vold <morten.vold@itea.ntnu.no>
#
####################

# Source function library.
. /usr/local/nav/navme/etc/init.d/functions

[ -x /usr/local/nav/navme/bin/smsd.pl ] || exit 1

# See how we were called.
case "$1" in
	start)
		# Start daemons.
		echo -n "Starting smsd.pl: "
		rc= daemon /usr/local/nav/navme/bin/smsd.pl
		echo
		exit $rc
		;;
	stop)
		# Stop daemons.
		echo -n "Shutting down smsd.pl: "
		if killproc smsd.pl; then
		# Make sure the pidfile is gone when stopping normal
		    rm -f /usr/local/nav/local/var/run/smsd.pl.pid
		    echo
		    exit 0
		else
		    echo
		    exit 1
		fi
        	;;
	restart)
		$0 stop
		$0 start
		;;
	status)
	        status smsd.pl
		exit $?
		;;
	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
esac

exit 0

# === End of File ===
