		<h1>
			<center>
				<font color=#000066>
					navAdmin - vlanPlot config - Main menu
				</font>
			</center>
		</h1>

		<center>
				<table border="0">
				  <tr>
						<td>
							<a href="[/link.vp.conf.enkel]">Enkel config</a>
						</td>
						<td>
							Konfigurasjon av enkle direktiver
						</td>
					</tr>
				  <tr>
						<td>
							<a href="[/link.vp.conf.grupper]">Gruppe config</a>
						</td>
						<td>
							Konfigurasjon av grupper
						</td>
					</tr>
				  <tr>
						<td>
							<a href="[/link.vp.conf.database]">Database config</a>
						</td>
						<td>
							Konfigurasjon av hvilken informasjon som skal tas med fra databasen
						</td>
					</tr>

				</table>
		</center>
