		<h1>
			<center>
				<font color=#000066>
					navAdmin - please login
				</font>
			</center>
		</h1>

		<center>
			<form action="[/main.servletPath]" METHOD="POST">
				<table border="0">
				  <tr>
						<td>
							User:
						</td>
						<td>
							<input type="text" name="login" size="20">
						</td>
					</tr>
				  <tr>
						<td>
							Password:
						</td>
						<td>
							<input type="password" name="pass" size="20">
						</td>
					</tr>
					<tr>
						<td colspan="2">
							<input type="submit" value="Logg inn" name="B1"><input type="reset" value="Blank" name="B2">
						</td>
					</tr>
				</table>
			</form>
		</center>
