		<h1>
			<center>
				<font color=#000066>
					navAdmin - Rapporter - Main menu
				</font>
			</center>
		</h1>

		<center>
				<table border="0">
<!--
				  <tr>
						<td>
							<a href="[/link.ni.listSwport]">Vis swport</a>
						</td>
						<td>
							Viser swport-tabellen i tre-struktur
						</td>
					</tr>
-->
<!--
				  <tr>
						<td>
							<a href="[/link.ni.checkError]">Sjekk for feil</a>
						</td>
						<td>
							Sjekk for feil i swport og NTNUnet tabellene
						</td>
					</tr>
-->

				  <tr>
						<td>
							<a href="/navAdminReports/" target="_blank">Rapporter</a>
						</td>
						<td>
							Alle rapporter fra nattlig kjøring av navAdmin
						</td>
					</tr>

					<tr>
					 <td>
					  <br>
					 <td>
					</tr>

				  <tr>
						<td>
							<a href="/navAdminReports/avledTopologi.html">Avled topologi</a>
						</td>
						<td>
							Vis rapport fra topologi avlederen.
						</td>
					</tr>
				  <tr>
						<td>
							<a href="/navAdminReports/avledVlan.html">Avled vlan</a>
						</td>
						<td>
							Vis rapport fra vlan avlederen.
						</td>
					</tr>

[/ni.ifRapporter]
				  <tr>
						<td>
							<a href="[/link.ni.avledTopologi]">Avled topologi</a>
						</td>
						<td>
							Avleder topologien i nettet med MAC data fra SNMP
						</td>
					</tr>

				  <tr>
						<td>
							<a href="[/link.ni.avledVlan]">Avled vlan</a>
						</td>
						<td>
							Avleder hvilke vlan som kjører på de forskjellige trunkene
						</td>
					</tr>
[/ni.ifRapporter.end]
<!--
				  <tr>
						<td>
							<a href="[/link.ni.updateMac]">Oppdater nettelMac</a>
						</td>
						<td>
							Oppdater nettelMac tabellen med MAC-adresser for alle enhetene i nettel.
						</td>
					</tr>
-->
<!--
				  <tr>
						<td>
							<a href="[/link.ni.updatePortBak]">Oppdater portBak</a>
						</td>
						<td>
							Oppdater portBak-feltet i swport med data fra SNMP
						</td>
					</tr>
-->
<!--
				  <tr>
						<td>
							<a href="[/link.ni.updateStatic]">Oppdater statiske innslag</a>
						</td>
						<td>
							Oppdater de statiske innslagene i swport for downlinker uten tilsvarende uplink
						</td>
					</tr>
-->
<!--
				  <tr>
						<td>
							<a href="[/link.ni.findMissingLinks]">Finn manglende linker</a>
						</td>
						<td>
							Oppdater de statiske innslagene i swport med kantutstyr ikke koblet direkte på kjernesvitsj
						</td>
					</tr>
-->

<!--
				  <tr>
						<td>
							<a href="[/link.ni.listkant]">listkant</a>
						</td>
						<td>
							Gammel listkant, tas bort straks vis swport er i drift
						</td>
					</tr>
-->
<!--
				  <tr>
						<td>
							<a href="[/link.ni.updateCommunity]">Update community</a>
						</td>
						<td>
							Oppdater community-tabell fra nettel.ntnu
						</td>
					</tr>
-->

				</table>
		</center>
