#!/usr/bin/env python

"""
Autogenerated by CHEETAH: The Python-Powered Template Engine
 CHEETAH VERSION: 0.9.15
 Generation time: Wed Oct  1 07:16:46 2003
   Source file: EmotdTemplate.tmpl
   Source file last modified: Wed Oct  1 06:10:33 2003
"""

__CHEETAH_genTime__ = 'Wed Oct  1 07:16:46 2003'
__CHEETAH_src__ = 'EmotdTemplate.tmpl'
__CHEETAH_version__ = '0.9.15'

##################################################
## DEPENDENCIES

import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from nav.web.templates.MainTemplate import MainTemplate
from nav.web.templates.TreeSelectTemplate import TreeSelectTemplate
from nav.web.templates.SearchBoxTemplate import SearchBoxTemplate
from mx import DateTime

##################################################
## MODULE CONSTANTS

try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFS=valueFromSearchList
VFN=valueForName
currentTime=time.time

##################################################
## CLASSES

class EmotdTemplate(MainTemplate):
    """
    
    Autogenerated by CHEETAH: The Python-Powered Template Engine
    """

    ##################################################
    ## GENERATED METHODS


    def __init__(self, *args, **KWs):
        """
        
        """

        MainTemplate.__init__(self, *args, **KWs)

    def content(self,
            trans=None,
            dummyTrans=False,
            VFS=valueFromSearchList,
            VFN=valueForName,
            getmtime=getmtime,
            currentTime=time.time,
            globals=globals,
            locals=locals,
            __builtin__=__builtin__):


        """
        Generated from #def content at line 13, col 1.
        """

        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        write = trans.response().write
        SL = self._searchList
        filter = self._currentFilter
        globalSetVars = self._globalSetVars
        
        ########################################
        ## START - generated method body
        
        if VFS(SL + [globals(), __builtin__],"menu",1):
            write(filter(VFS(SL + [globals(), __builtin__],"menu",1), rawExpr='$menu')) # from line 15, col 1.
            write('\n')
        if VFS(SL + [globals(), __builtin__],"body",1):
            write(filter(VFS(SL + [globals(), __builtin__],"body",1), rawExpr='$body')) # from line 18, col 1.
            write('\n')
        if VFS(SL + [globals(), __builtin__],"motd",1):
            numemotds = VFS(SL + [globals(), __builtin__],"len",0)(VFS(SL + [globals(), __builtin__],"motd",1))
            write('''<table width=600 BACKGROUND-COLOR: #ffffff; BORDER-BOTTOM: #000099 thin solid; BORDER-LEFT: #000099 thin solid; BORDER-RIGHT: #000099 thin solid; BORDER-TOP: #000099 thin solid; PADDING-BOTTOM: 0px; PADDING-LEFT: 0px; PADDING-RIGHT: 0px; PADDING-TOP: 0px>
<tr class="title">
<td class="title" align="center" colspan="5" style="background-image:url('/images/emotd/emotdlogo+fill.gif'); background-repeat: no-repeat;">  
<table class="navigation" cellspacing="0" cellpadding="0" border="0">
<tr class="navigation">
<td class="current">
<div class="title"><font color="black"><a href=/emotd/>Message of the day</a></font><br>
''')
            write(filter(VFS(SL + [globals(), __builtin__],"title",1), rawExpr='$title')) # from line 29, col 1.
            write('''
</b></div> 
</TD></TR>
</table>
</td></tr>
''')
            for message in VFS(SL + [globals(), __builtin__],"motd",1):
                write('<tr>\n<td colspan="2" align=left >\n<b>Title:</b> ')
                write(filter(VFN(message,"title",1), rawExpr='$message.title')) # from line 37, col 15.
                write(''' 
</td>
<td colspan="3" align=right>
<b>''')
                write(filter(VFN(message,"last_changed",1), rawExpr='$message.last_changed')) # from line 40, col 4.
                write(' </b> by <b> ')
                write(filter(VFN(message,"author",1), rawExpr='$message.author')) # from line 40, col 38.
                write('''</b>

</td>
</tr>
''')
                if not VFN(message,"affected",1) == None or "":
                    write('<tr><td colspan="5"><b>Affected end users:</b> ')
                    write(filter(VFN(message,"affected",1), rawExpr='$message.affected')) # from line 45, col 48.
                    write('</td></tr>\n')
                if not VFN(message,"downtime",1) == None or "":
                    write('<tr><td colspan="5"><b>Estimated downtime:</b> ')
                    write(filter(VFN(message,"downtime",1), rawExpr='$message.downtime')) # from line 48, col 48.
                    write('</td></tr>\n<tr><td colspan="5"><b>MOTD Type:</b> ')
                    write(filter(VFN(message,"type",1), rawExpr='$message.type')) # from line 49, col 39.
                    write(' \n')
                    if VFN(message,"type",1) == "internal":
                        write('<i>For NAV users eyes only</i>\n')
                    write('</td></tr>\n')
                write('<tr>\n<td colspan=5><b>Description:</b><br> \n')
                write(filter(VFN(message,"description",1), rawExpr='$message.description')) # from line 57, col 1.
                write(' </td>\n</tr>\n')
                if numemotds == 1:
                    if VFN(message,"detail",1):
                        write('<tr>\n<td colspan=5><b>Details:</b><br>\n')
                        write(filter(VFN(message,"detail",1), rawExpr='$message.detail')) # from line 63, col 1.
                        write('</td>\n</tr>\n')
                else:
                    write('<tr>\n<td colspan=5><b><a href=/emotd/view?id=')
                    write(filter(VFN(message,"emotdid",1), rawExpr='$message.emotdid')) # from line 68, col 41.
                    write('''>Read more...</b>
</td>
</tr>
''')
                if not VFN(message,"replaces_emotd",1) == None:
                    write('<tr><td colspan="5"><a href=/emotd/view?id=')
                    write(filter(VFN(message,"replaces_emotd",1), rawExpr='$message.replaces_emotd')) # from line 73, col 44.
                    write('>Previous</a> message in thread\n</td></tr>\n')
                write('<tr><td colspan="5"><hr></td></tr>\n')
            write('</table>\n')
        write('\n')
        if VFS(SL + [globals(), __builtin__],"searchBox",1):
            write(filter(VFN(VFS(SL + [globals(), __builtin__],"SearchBoxTemplate",0)(),"searchbox",0)(VFS(SL + [globals(), __builtin__],"searchBox",1)), rawExpr='$SearchBoxTemplate().searchbox($searchBox)')) # from line 82, col 1.
            write('\n<form method="post">\n')
            if VFS(SL + [globals(), __builtin__],"form",1):
                write(filter(VFS(SL + [globals(), __builtin__],"form",1), rawExpr='$form')) # from line 85, col 1.
                write('\n')
            write(filter(VFN(VFS(SL + [globals(), __builtin__],"TreeSelectTemplate",0)(),"treeselect",0)(VFS(SL + [globals(), __builtin__],"selectBox",1)), rawExpr='$TreeSelectTemplate().treeselect($selectBox)')) # from line 87, col 1.
            write('''
<input type=submit name="submitbutton" value="Set on maintenance">
</form>
''')
        
        ########################################
        ## END - generated method body
        
        if dummyTrans:
            return trans.response().getvalue()
        else:
            return ""
        

    def is_even(self,
            s,
            trans=None,
            dummyTrans=False,
            VFS=valueFromSearchList,
            VFN=valueForName,
            getmtime=getmtime,
            currentTime=time.time,
            globals=globals,
            locals=locals,
            __builtin__=__builtin__):


        """
        Generated from #def is_even(s) at line 93, col 1.
        """

        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        write = trans.response().write
        SL = self._searchList
        filter = self._currentFilter
        globalSetVars = self._globalSetVars
        
        ########################################
        ## START - generated method body
        
        if s % 2 == 0:
            write('<td style="border-top: 1px solid white; border-left: 1px solid white; background-color: #eee;>\n')
        else:
            write('<td style="border-bottom: 1px solid white; border-left: 1px solid white; border-right: 1px solid white;>\n')
        
        ########################################
        ## END - generated method body
        
        if dummyTrans:
            return trans.response().getvalue()
        else:
            return ""
        

    def writeBody(self,
            trans=None,
            dummyTrans=False,
            VFS=valueFromSearchList,
            VFN=valueForName,
            getmtime=getmtime,
            currentTime=time.time,
            globals=globals,
            locals=locals,
            __builtin__=__builtin__):


        """
        This is the main method generated by Cheetah
        """

        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        write = trans.response().write
        SL = self._searchList
        filter = self._currentFilter
        globalSetVars = self._globalSetVars
        
        ########################################
        ## START - generated method body
        
        #  EmotdTemplate
        write('\n')
        #  Inheritance and modules
        write('\n')
        #  Variables
        sb = SearchBoxTemplate()
        ts = TreeSelectTemplate()
        write('\n\n')
        
        ########################################
        ## END - generated method body
        
        if dummyTrans:
            return trans.response().getvalue()
        else:
            return ""
        
    ##################################################
    ## GENERATED ATTRIBUTES


    _mainCheetahMethod_for_EmotdTemplate= 'writeBody'


# CHEETAH was developed by Tavis Rudd, Mike Orr, Ian Bicking and Chuck Esterbrook;
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org

##################################################
## if run from command line:
if __name__ == '__main__':
    EmotdTemplate().runAsMainProgram()

