#!/usr/bin/env python

"""
Autogenerated by CHEETAH: The Python-Powered Template Engine
 CHEETAH VERSION: 0.9.15
 Generation time: Wed Oct  1 07:16:46 2003
   Source file: EmotdFrontpage.tmpl
   Source file last modified: Wed Oct  1 07:16:42 2003
"""

__CHEETAH_genTime__ = 'Wed Oct  1 07:16:46 2003'
__CHEETAH_src__ = 'EmotdFrontpage.tmpl'
__CHEETAH_version__ = '0.9.15'

##################################################
## DEPENDENCIES

import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from nav.web.templates.MainTemplate import MainTemplate

##################################################
## MODULE CONSTANTS

try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFS=valueFromSearchList
VFN=valueForName
currentTime=time.time

##################################################
## CLASSES

class EmotdFrontpage(MainTemplate):
    """
    
    Autogenerated by CHEETAH: The Python-Powered Template Engine
    """

    ##################################################
    ## GENERATED METHODS


    def __init__(self, *args, **KWs):
        """
        
        """

        MainTemplate.__init__(self, *args, **KWs)

    def content(self,
            trans=None,
            dummyTrans=False,
            VFS=valueFromSearchList,
            VFN=valueForName,
            getmtime=getmtime,
            currentTime=time.time,
            globals=globals,
            locals=locals,
            __builtin__=__builtin__):


        """
        Generated from #block content at line 7, col 1.
        """

        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        write = trans.response().write
        SL = self._searchList
        filter = self._currentFilter
        globalSetVars = self._globalSetVars
        
        ########################################
        ## START - generated method body
        
        write('''    <table border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td valign="top" width="190">
     ''')
        write(filter(VFS(SL + [globals(), __builtin__],"emotdlinksbox",1), rawExpr='$emotdlinksbox')) # from line 11, col 6.
        write(''' <br>
        </td>
        <td valign="top">
        <table border="0" cellspacing="0" cellpadding="0"><tr><td>
     ''')
        write(filter(VFS(SL + [globals(), __builtin__],"emotd",0)(VFS(SL + [globals(), __builtin__],"emotds",1)), rawExpr='$emotd($emotds)')) # from line 15, col 6.
        write('''
        </td></tr>
        </table>
      </tr>
    </table>
''')
        
        ########################################
        ## END - generated method body
        
        if dummyTrans:
            return trans.response().getvalue()
        else:
            return ""
        

    def emotdlinksbox(self,
            trans=None,
            dummyTrans=False,
            VFS=valueFromSearchList,
            VFN=valueForName,
            getmtime=getmtime,
            currentTime=time.time,
            globals=globals,
            locals=locals,
            __builtin__=__builtin__):


        """
        Generated from #def $emotdlinksbox at line 22, col 1.
        """

        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        write = trans.response().write
        SL = self._searchList
        filter = self._currentFilter
        globalSetVars = self._globalSetVars
        
        ########################################
        ## START - generated method body
        
        write('  ')
        write(filter(VFS(SL + [globals(), __builtin__],"sideboxstart",0)('EMOTD'), rawExpr="$sideboxstart('EMOTD')")) # from line 23, col 3.
        write('\n  ')
        write(filter(VFS(SL + [globals(), __builtin__],"motdlinks",1), rawExpr='$motdlinks')) # from line 24, col 3.
        write('\n  ')
        write(filter(VFS(SL + [globals(), __builtin__],"sideboxend",0)(), rawExpr='$sideboxend()')) # from line 25, col 3.
        write('\n')
        
        ########################################
        ## END - generated method body
        
        if dummyTrans:
            return trans.response().getvalue()
        else:
            return ""
        

    def motdlinks(self,
            trans=None,
            dummyTrans=False,
            VFS=valueFromSearchList,
            VFN=valueForName,
            getmtime=getmtime,
            currentTime=time.time,
            globals=globals,
            locals=locals,
            __builtin__=__builtin__):


        """
        Generated from #def motdlinks at line 28, col 1.
        """

        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        write = trans.response().write
        SL = self._searchList
        filter = self._currentFilter
        globalSetVars = self._globalSetVars
        
        ########################################
        ## START - generated method body
        
        write('  ')
        write(filter(VFS(SL + [globals(), __builtin__],"menu",1), rawExpr='$menu')) # from line 29, col 3.
        write('\n')
        
        ########################################
        ## END - generated method body
        
        if dummyTrans:
            return trans.response().getvalue()
        else:
            return ""
        

    def sideboxstart(self,
            title,
            trans=None,
            dummyTrans=False,
            VFS=valueFromSearchList,
            VFN=valueForName,
            getmtime=getmtime,
            currentTime=time.time,
            globals=globals,
            locals=locals,
            __builtin__=__builtin__):


        """
        Generated from #def sideboxstart($title) at line 32, col 1.
        """

        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        write = trans.response().write
        SL = self._searchList
        filter = self._currentFilter
        globalSetVars = self._globalSetVars
        
        ########################################
        ## START - generated method body
        
        write('''  <table border="0" cellspacing="0" cellpadding="3" width="100%" class="sidebox">
    <tr>
      <td class="sideboxtitle">
        ''')
        write(filter(title, rawExpr='$title')) # from line 36, col 9.
        write('''
      </td>
    </tr>
    <tr>
      <td class="sideboxlinks">
''')
        
        ########################################
        ## END - generated method body
        
        if dummyTrans:
            return trans.response().getvalue()
        else:
            return ""
        

    def sideboxend(self,
            trans=None,
            dummyTrans=False,
            VFS=valueFromSearchList,
            VFN=valueForName,
            getmtime=getmtime,
            currentTime=time.time,
            globals=globals,
            locals=locals,
            __builtin__=__builtin__):


        """
        Generated from #def sideboxend at line 43, col 1.
        """

        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        write = trans.response().write
        SL = self._searchList
        filter = self._currentFilter
        globalSetVars = self._globalSetVars
        
        ########################################
        ## START - generated method body
        
        write('''      </td>
    </tr>
  </table>
''')
        
        ########################################
        ## END - generated method body
        
        if dummyTrans:
            return trans.response().getvalue()
        else:
            return ""
        

    def emotd(self,
            emotds,
            trans=None,
            dummyTrans=False,
            VFS=valueFromSearchList,
            VFN=valueForName,
            getmtime=getmtime,
            currentTime=time.time,
            globals=globals,
            locals=locals,
            __builtin__=__builtin__):


        """
        Generated from #def emotd($emotds) at line 49, col 1.
        """

        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        write = trans.response().write
        SL = self._searchList
        filter = self._currentFilter
        globalSetVars = self._globalSetVars
        
        ########################################
        ## START - generated method body
        
        write('  <br>\n')
        antemotds = len(emotds)
        write('  <table width="100%" cellspacing="0" cellpadding="0" border="0">\n    <tr class="title">\n      <td class="title" align="center" colspan="3" style="background-image:url(\'')
        write(filter(VFS(SL + [globals(), __builtin__],"imagefolder",1), rawExpr='$imagefolder')) # from line 54, col 81.
        write('''/emotd/emotdlogo+fill.gif'); background-repeat: no-repeat;">
        <table class="navigation" cellspacing="0" cellpadding="0" border="0">
          <tr class="navigation">
            <td class="current">
              <div class="title"><a href="/emotd/"><font color="black">Messages of the Day</font></a></div>
''')
        if antemotds == 0:
            write('               No messages\n')
        elif antemotds == 1:
            write('               Showing message\n')
        else:
            write('               Showing ')
            write(filter(antemotds, rawExpr='$antemotds')) # from line 64, col 24.
            write(' messages\n')
        write('''            </td>
          </tr>
        </table>
      </td>
      <td align=right style="background-image:url(\'''')
        write(filter(VFS(SL + [globals(), __builtin__],"imagefolder",1), rawExpr='$imagefolder')) # from line 70, col 52.
        write('/arpcam/fill.gif\');"><img src="')
        write(filter(VFS(SL + [globals(), __builtin__],"imagefolder",1), rawExpr='$imagefolder')) # from line 70, col 95.
        write('''/ragen/top-end.gif"></td>
    </tr>
  </table>
  <table width="100%" cellspacing="0" cellpadding="0" border="0">
''')
        for message in emotds:
            write('''    <tr>
      <td style="border-top: 1px solid white; border-left: 1px solid white; background-color: #eee;">
        <b>Title:</b>
''')
            if antemotds > 1:
                write('          <a href="/emotd/view?id=')
                write(filter(VFN(message,"emotdid",1), rawExpr='$message.emotdid')) # from line 79, col 35.
                write('">')
                write(filter(VFN(message,"title",1), rawExpr='$message.title')) # from line 79, col 53.
                write('</a>\n')
            else:
                write('          ')
                write(filter(VFN(message,"title",1), rawExpr='$message.title')) # from line 81, col 11.
                write('\n')
            write('      </td>\n      <td align="right" style="border-top: 1px solid white; border-right: 1px solid white; background-color: #eee; font-size: 11px">\n      ')
            write(filter(VFN(message,"last_changed",1), rawExpr='$message.last_changed')) # from line 85, col 7.
            write(' </td>\n      <td align="right" style="border-top: 1px solid white; border-right: 1px solid white; background-color: #eee; font-size: 11px">\n      by ')
            write(filter(VFN(message,"author",1), rawExpr='$message.author')) # from line 87, col 10.
            write('''
      </td>
    </tr>
''')
            if antemotds == 1:
                write('')
                if VFN(message,"affected",1) != None or '':
                    write('    <tr>\n      <td colspan="3" style="border-bottom: 1px solid white; border-left: 1px solid white; border-right: 1px solid white;">\n      Affected users: ')
                    write(filter(VFN(message,"affected",1), rawExpr='$message.affected')) # from line 94, col 23.
                    write('''
      </td>
    </tr>
''')
                write('')
                if VFN(message,"affected",1) != None or '':
                    write('    <tr>\n      <td colspan="3" style="border-bottom: 1px solid white; border-left: 1px solid white; border-right: 1px solid white;">\n      Estimated downtime: ')
                    write(filter(VFN(message,"downtime",1), rawExpr='$message.downtime')) # from line 101, col 27.
                    write('''
      </td>
    </tr>
''')
                write('')
            write('    <tr>\n      <td colspan="3" style="border-bottom: 1px solid white; border-left: 1px solid white; border-right: 1px solid white;">\n        <b>Description:</b><br>')
            write(filter(VFN(message,"description",1), rawExpr='$message.description')) # from line 108, col 32.
            write('''
      </td>
    </tr>
''')
            if antemotds == 1:
                write('')
                #  show the rest
                write('    <tr>\n      <td colspan="3" style="border-bottom: 1px solid white; border-left: 1px solid white; border-right: 1px solid white;">\n        <b>Details:</b> <br>')
                write(filter(VFN(message,"detail",1), rawExpr='$message.detail')) # from line 115, col 29.
                write('''
      </td>
    </tr>
''')
            write('')
            if VFS(SL + [globals(), __builtin__],"access",1) == True:
                write('    <tr>\n      <td colspan="3" style="border-top: 1px solid white; border-left: 1px solid white; background-color: #eee;">\n        <a href=/emotd/edit?id=')
                write(filter(VFN(message,"emotdid",1), rawExpr='$message.emotdid')) # from line 122, col 32.
                write('&action=change>Change</a> * \n        <a href=/emotd/edit?id=')
                write(filter(VFN(message,"emotdid",1), rawExpr='$message.emotdid')) # from line 123, col 32.
                write('''&action=followup>Followup</a>  
      </td>
    </tr>
''')
            write('')
            if not antemotds == 1 or 0:
                write('''    <tr>
      <td colspan="3" style="border-bottom: 1px solid white; border-left: 1px solid white; border-right: 1px solid white;">
       <hr>
      </td>
    </tr>
''')
            write('')
        write('  </table>\n')
        
        ########################################
        ## END - generated method body
        
        if dummyTrans:
            return trans.response().getvalue()
        else:
            return ""
        

    def additionalCSS(self,
            trans=None,
            dummyTrans=False,
            VFS=valueFromSearchList,
            VFN=valueForName,
            getmtime=getmtime,
            currentTime=time.time,
            globals=globals,
            locals=locals,
            __builtin__=__builtin__):


        """
        Generated from #block additionalCSS at line 139, col 1.
        """

        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        write = trans.response().write
        SL = self._searchList
        filter = self._currentFilter
        globalSetVars = self._globalSetVars
        
        ########################################
        ## START - generated method body
        
        write('''      TD {
      font-family: verdana, arial, helvetica, sans-serif;
      font-size: 13;
      }

      TD.smallfont {
      font-size: 11;
      }
     
      td.sideboxlinks {
      font-size: 11;
      border: 1px solid #ccc;
      }

      td.sideboxtitle {
      font-size: 13;
      border: 1px solid #000;
      text-align: center;
      background-image:url('/images/form/fill-active.gif');
      background-color:#ccf;
      }
      
''')
        write(filter(VFS(SL + [globals(), __builtin__],"default_table_CSS",1), rawExpr='$default_table_CSS')) # from line 162, col 1.
        write('\n')
        
        ########################################
        ## END - generated method body
        
        if dummyTrans:
            return trans.response().getvalue()
        else:
            return ""
        

    def writeBody(self,
            trans=None,
            dummyTrans=False,
            VFS=valueFromSearchList,
            VFN=valueForName,
            getmtime=getmtime,
            currentTime=time.time,
            globals=globals,
            locals=locals,
            __builtin__=__builtin__):


        """
        This is the main method generated by Cheetah
        """

        if not trans:
            trans = DummyTransaction()
            dummyTrans = True
        write = trans.response().write
        SL = self._searchList
        filter = self._currentFilter
        globalSetVars = self._globalSetVars
        
        ########################################
        ## START - generated method body
        
        write('''


''')
        self.content(trans=trans) # generated from ('content', '#block content') at line 7, col 1.
        write('''






''')
        self.additionalCSS(trans=trans) # generated from ('additionalCSS', '#block additionalCSS') at line 139, col 1.
        write('\n')
        
        ########################################
        ## END - generated method body
        
        if dummyTrans:
            return trans.response().getvalue()
        else:
            return ""
        
    ##################################################
    ## GENERATED ATTRIBUTES


    numberOfMessagesShown = 15

    access = False

    _mainCheetahMethod_for_EmotdFrontpage= 'writeBody'


# CHEETAH was developed by Tavis Rudd, Mike Orr, Ian Bicking and Chuck Esterbrook;
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org

##################################################
## if run from command line:
if __name__ == '__main__':
    EmotdFrontpage().runAsMainProgram()

