name: Build docker compose dev environment
on:
  schedule:
    - cron: '6 6 * * *'
  push:
    branches:
      - master
      - '[1-9][0-9]?.[0-9]+.x'
  pull_request:

jobs:
  build-docker-compose:
    name: "Build docker-compose-based development environment"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: docker compose build
        run: |
          echo "UID=$(id -u)" >> .env
          echo "GID=$(id -g)" >> .env
          docker compose build

      - name: Verify containers stay running at least 1 minute
        run: |
          docker compose up -d
          sleep 60
          docker compose ps
          echo "Verifying service states"
          docker compose ps -q | xargs docker inspect -f '{{.State.Running}}' | grep -q false && exit 1
          echo "Looks ok"

      - name: Print docker compose logs
        if: failure()
        run: |
          docker compose logs

      - name: Check for Slack secret availability (on fork or not)
        id: slack-secret-check
        if: failure()
        shell: bash
        run: |
          if [ "${{ secrets.SLACK_WEBHOOK_URL }}" != '' ]; then
            echo "slack_available=true" >> $GITHUB_OUTPUT;
          else
            echo "slack_available=false" >> $GITHUB_OUTPUT;
          fi

      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        if: ${{ failure() && steps.slack-secret-check.outputs.slack_available == 'true' }}
        uses: slackapi/slack-github-action@v3.0.3
        with:
          payload: |
            {
              "title": "Building NAV's Docker Compose dev environment failed",
              "github_ref_name": "${{ github.ref_name }}",
              "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
